import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const articles: TopicSeed = {
  id: "topic-articles",
  slug: "articles",
  name: "Articles",
  gradeFrom: 6,
  gradeTo: 12,
  summary: "a/an cho danh từ đếm được số ít chưa xác định; the khi cả người nói và nghe đều biết đối tượng.",
  purpose:
    "Đánh dấu danh từ là chưa xác định (a/an), đã xác định (the), hoặc nói chung không cần mạo từ trong một số trường hợp.",
  usage: [
    "a: đứng trước âm phụ âm.",
    "an: đứng trước âm nguyên âm theo cách đọc (an hour, an umbrella).",
    "the: khi đã nhắc trước, chỉ một thứ duy nhất, hoặc cả hai bên đều hiểu.",
    "Không dùng a / an: với danh từ không đếm được, hoặc số nhiều khi nói chung.",
  ].join("\n"),
  structure: [
    "a / an + danh từ đếm được số ít: khi nhắc lần đầu.",
    "the + danh từ: khi danh từ đã xác định.",
    "Không mạo từ: danh từ số nhiều hoặc không đếm được khi nói chung (Books are useful; Water is essential).",
  ].join("\n"),
  affirmativePattern: "There is a/an + danh từ số ít. The + danh từ đã biết + động từ.",
  negativePattern: "There isn't a/an + danh từ số ít. I don't have the + danh từ đã xác định.",
  questionPattern: "Is there a/an + danh từ? Where is the + danh từ đã biết?",
  signalWords: [
    "a",
    "an",
    "the",
    "first mention",
    "the only one",
    "same for speaker and listener",
  ],
  examples: [
    {
      sentence: "I saw a cat in the garden. The cat was black.",
      note: "Lần đầu dùng a; lần sau đã biết nên the.",
    },
    {
      sentence: "She is an honest student.",
      note: "honest bắt đầu bằng nguyên âm /ɒ/, nên an.",
    },
    {
      sentence: "The sun rises in the east.",
      note: "sun và east là đối tượng duy nhất/đã quy ước, dùng the.",
    },
    {
      sentence: "Milk is good for bones.",
      note: "Nói chung về milk (không đếm được) thường không dùng a/the.",
    },
  ],
  commonMistakes: [
    {
      wrong: "I need an university.",
      right: "I need a university.",
      why: "university phát âm /juː/, bắt đầu bằng phụ âm, dùng a.",
    },
    {
      wrong: "She bought a apple.",
      right: "She bought an apple.",
      why: "apple bắt đầu bằng nguyên âm /æ/, dùng an.",
    },
    {
      wrong: "I saw a dog. A dog was hungry.",
      right: "I saw a dog. The dog was hungry.",
      why: "Đã nhắc lần trước thì lần sau dùng the.",
    },
  ],
  comparisons: [
    {
      with: "Zero article",
      note: "a/an giới thiệu một đơn vị chưa xác định. the chỉ đối tượng đã biết. Không mạo từ khi nói chung với số nhiều hoặc không đếm được: Dogs bark; Happiness matters.",
    },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "art-1",
      difficulty: "easy",
      stem: "She wants to buy ___ umbrella because it is raining.",
      choices: {
        a: "a",
        b: "an",
        c: "the",
        d: "— (no article)",
      },
      answer: "b",
      explanation: "umbrella bắt đầu bằng nguyên âm /ʌ/, lần đầu chưa xác định → an.",
      whyWrong: {
        a: "a đứng trước phụ âm, không trước umbrella.",
        c: "the dùng khi đã biết chiếc ô cụ thể; câu này mới giới thiệu.",
        d: "Danh từ đếm được số ít cần a/an khi nói một cái chưa xác định.",
      },
    }),
    mcq({
      id: "art-2",
      difficulty: "easy",
      stem: "I saw ___ dog outside. ___ dog looked friendly.",
      choices: {
        a: "a / A",
        b: "a / The",
        c: "the / A",
        d: "an / The",
      },
      answer: "b",
      explanation: "Lần đầu a dog; lần sau đã xác định nên The dog.",
      whyWrong: {
        a: "A dog lần hai vẫn chưa xác định, sai quy tắc đã nhắc.",
        c: "the dog lần đầu khi chưa nhắc là quá sớm.",
        d: "an không đi với dog (phụ âm /d/).",
      },
    }),
    mcq({
      id: "art-3",
      difficulty: "easy",
      stem: "He is ___ honest man.",
      choices: {
        a: "a",
        b: "an",
        c: "the",
        d: "— (no article)",
      },
      answer: "b",
      explanation: "honest phát âm bắt đầu bằng nguyên âm /ɒ/, dùng an.",
      whyWrong: {
        a: "a không đứng trước âm nguyên âm của honest.",
        c: "the không cần khi chỉ một người chưa xác định theo nghĩa 'một người thành thật'.",
        d: "Danh từ số ít đếm được man cần mạo từ ở đây.",
      },
    }),
    mcq({
      id: "art-4",
      difficulty: "easy",
      stem: "___ moon looks bright tonight.",
      choices: {
        a: "A",
        b: "An",
        c: "The",
        d: "— (no article)",
      },
      answer: "c",
      explanation: "moon là đối tượng duy nhất theo quy ước, dùng The.",
      whyWrong: {
        a: "A moon gợi ý một mặt trăng bất kỳ, không phải cách nói chuẩn.",
        b: "An không khớp moon và cũng sai nghĩa duy nhất.",
        d: "Thiếu the trước moon trong câu này.",
      },
    }),
    mcq({
      id: "art-5",
      difficulty: "medium",
      stem: "She goes to school by ___ bus every day.",
      choices: {
        a: "a",
        b: "an",
        c: "the",
        d: "— (no article)",
      },
      answer: "d",
      explanation: "by bus là cách đi lại theo phương tiện nói chung, không dùng mạo từ.",
      whyWrong: {
        a: "by a bus không phải cụm giao thông chuẩn khi nói phương tiện nói chung.",
        b: "an không đi với bus.",
        c: "by the bus chỉ khi nói một chuyến xe đã xác định, không phải thói quen every day.",
      },
    }),
    mcq({
      id: "art-6",
      difficulty: "medium",
      stem: "Can you open ___ window, please? It is hot in here.",
      choices: {
        a: "a",
        b: "an",
        c: "the",
        d: "— (no article)",
      },
      answer: "c",
      explanation: "Cả hai đều hiểu cửa sổ trong phòng → the window.",
      whyWrong: {
        a: "a window nghe như bất kỳ cửa sổ nào, kém tự nhiên khi đang ở trong phòng.",
        b: "an không đi với window.",
        d: "window số ít đếm được cần mạo từ ở đây.",
      },
    }),
    mcq({
      id: "art-7",
      difficulty: "medium",
      stem: "My brother wants to be ___ engineer.",
      choices: {
        a: "a",
        b: "an",
        c: "the",
        d: "— (no article)",
      },
      answer: "b",
      explanation: "engineer bắt đầu bằng nguyên âm /e/, nghề nghiệp lần đầu → an engineer.",
      whyWrong: {
        a: "a không đứng trước âm nguyên âm của engineer.",
        c: "the engineer chỉ một kỹ sư đã xác định, không phải nghề muốn trở thành nói chung.",
        d: "Nghề với be thường cần a/an.",
      },
    }),
    mcq({
      id: "art-8",
      difficulty: "medium",
      stem: "___ water in this bottle is cold.",
      choices: {
        a: "A",
        b: "An",
        c: "The",
        d: "— (no article)",
      },
      answer: "c",
      explanation: "water cụ thể trong chai này đã xác định → The water.",
      whyWrong: {
        a: "a không dùng với water không đếm được.",
        b: "an cũng không dùng với water không đếm được.",
        d: "Không mạo từ hợp khi nói water nói chung, nhưng ở đây đã chỉ 'trong chai này'.",
      },
    }),
    mcq({
      id: "art-9",
      difficulty: "hard",
      stem: "She studies at ___ university in Da Nang.",
      choices: {
        a: "a",
        b: "an",
        c: "the",
        d: "— (no article)",
      },
      answer: "a",
      explanation: "university phát âm /juː/ (phụ âm), lần đầu chưa chỉ trường cụ thể đã biết → a.",
      whyWrong: {
        b: "an sai vì âm đầu là /j/, không phải nguyên âm.",
        c: "the university chỉ khi cả hai đã biết trường nào.",
        d: "university số ít đếm được cần a/an khi chưa xác định.",
      },
    }),
    mcq({
      id: "art-10",
      difficulty: "hard",
      stem: "___ happiness is more important than money.",
      choices: {
        a: "A",
        b: "An",
        c: "The",
        d: "— (no article)",
      },
      answer: "d",
      explanation: "happiness là trừu tượng nói chung, thường không dùng mạo từ.",
      whyWrong: {
        a: "a happiness không chuẩn với danh từ trừu tượng nói chung.",
        b: "an happiness sai tương tự.",
        c: "the happiness chỉ khi nói một niềm hạnh phúc cụ thể đã xác định.",
      },
    }),
    mcq({
      id: "art-11",
      difficulty: "hard",
      stem: "We climbed ___ Mount Fansipan last summer.",
      choices: {
        a: "a",
        b: "an",
        c: "the",
        d: "— (no article)",
      },
      answer: "d",
      explanation: "Tên núi có Mount suffix thường không dùng the: Mount Fansipan.",
      whyWrong: {
        a: "a Mount Fansipan không phải cách đặt tên núi.",
        b: "an không dùng ở đây.",
        c: "the Mount Fansipan sai; khác với the Himalayas (dãy núi).",
      },
    }),
    mcq({
      id: "art-12",
      difficulty: "hard",
      stem: "He plays ___ piano very well, but he cannot play ___ football.",
      choices: {
        a: "the / the",
        b: "the / — (no article)",
        c: "a / the",
        d: "— (no article) / the",
      },
      answer: "b",
      explanation: "Nhạc cụ thường dùng the piano; môn thể thao dùng zero article: play football.",
      whyWrong: {
        a: "the football sai khi nói môn thể thao nói chung.",
        c: "a piano kém chuẩn hơn the piano cho kỹ năng chơi nhạc cụ; the football cũng sai.",
        d: "Thiếu the trước piano; thừa the trước football.",
      },
    }),
  ],
};
