import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const conditionalType1: TopicSeed = {
  id: "topic-conditional-1",
  slug: "conditional-type-1",
  name: "Conditional Type 1",
  gradeFrom: 9,
  gradeTo: 12,
  summary: "Điều kiện có thể xảy ra ở hiện tại hoặc tương lai.",
  purpose: "Nói kết quả có thật nếu điều kiện xảy ra.",
  usage: [
    "Mệnh đề if: dùng hiện tại đơn.",
    "Mệnh đề chính: will + động từ nguyên mẫu.",
    "unless: nghĩa là if not.",
  ].join("\n"),
  structure: [
    "Mẫu: If + hiện tại đơn, will + V.",
    "Đảo mệnh đề will lên trước: bỏ dấu phẩy.",
  ].join("\n"),
  affirmativePattern: "If + chủ ngữ + V/V-s, chủ ngữ + will + V.",
  negativePattern: "If + chủ ngữ + do/does not + V, chủ ngữ + will not + V.",
  questionPattern: "Will + chủ ngữ + V if + chủ ngữ + V?",
  signalWords: ["if", "unless", "as soon as", "provided that"],
  examples: [
    { sentence: "If it rains this afternoon, we will stay inside.", note: "Mưa là khả năng có thật." },
    { sentence: "If she studies every evening, she will pass.", note: "studies chia theo she trong mệnh đề if." },
    { sentence: "Unless you leave now, you will miss the bus.", note: "Unless thay cho if you do not." },
  ],
  commonMistakes: [
    { wrong: "If it will rain, we will stay inside.", right: "If it rains, we will stay inside.", why: "Mệnh đề if của loại 1 không dùng will." },
    { wrong: "If she will study, she passes.", right: "If she studies, she will pass.", why: "will đứng ở mệnh đề kết quả, không đứng sau if." },
    { wrong: "If I hear any news, I call you.", right: "If I hear any news, I will call you.", why: "Kết quả tương lai cần will, trừ khi cố ý nói thói quen." },
  ],
  comparisons: [
    { with: "Conditional type 2", note: "Loại 1 là điều có thể xảy ra: If it rains, I will stay. Loại 2 là giả định khác thực tế: If I were rich, I would travel." },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "c1-1",
      difficulty: "easy",
      stem: "If it rains this afternoon, we ___ inside.",
      choices: { a: "stay", b: "will stay", c: "stayed", d: "would stay" },
      answer: "b",
      explanation: "Điều kiện có thể xảy ra chiều nay, kết quả dùng will stay.",
      whyWrong: {
        a: "stay thiếu will cho kết quả tương lai.",
        c: "stayed là quá khứ, không phải kết quả loại 1.",
        d: "would stay thuộc câu điều kiện loại 2.",
      },
    }),
    mcq({
      id: "c1-2",
      difficulty: "easy",
      stem: "If she ___ every evening, she will pass the exam.",
      choices: { a: "study", b: "studies", c: "studied", d: "would study" },
      answer: "b",
      explanation: "Mệnh đề if loại 1 với she dùng studies.",
      whyWrong: {
        a: "study chưa chia cho she.",
        c: "studied đưa điều kiện thành loại 2, trong khi vế kia là will pass.",
        d: "would study không đứng trong if của loại 1.",
      },
    }),
    mcq({
      id: "c1-3",
      difficulty: "medium",
      stem: "Unless you leave now, you ___ the last bus.",
      choices: { a: "miss", b: "will miss", c: "missed", d: "would miss" },
      answer: "b",
      explanation: "Unless bạn không đi ngay, kết quả tương lai là will miss.",
      whyWrong: {
        a: "miss thiếu will.",
        c: "missed là quá khứ.",
        d: "would miss là giả định loại 2, câu này là khả năng có thật.",
      },
    }),
    mcq({
      id: "c1-4",
      difficulty: "medium",
      stem: "If they do not water the plant tonight, it ___ by tomorrow.",
      choices: { a: "dies", b: "will die", c: "died", d: "would die" },
      answer: "b",
      explanation: "by tomorrow chỉ kết quả phía trước, dùng will die.",
      whyWrong: {
        a: "dies hợp với quy luật chung, không với một cây cụ thể và mốc tomorrow.",
        c: "died là quá khứ.",
        d: "would die không đi với if + hiện tại đơn.",
      },
    }),
    mcq({
      id: "c1-5",
      difficulty: "hard",
      stem: "If I hear any news, I ___ you at once.",
      choices: { a: "call", b: "will call", c: "called", d: "would call" },
      answer: "b",
      explanation: "If I hear là hiện tại đơn, kết quả là will call.",
      whyWrong: {
        a: "call bỏ mất will của mệnh đề kết quả.",
        c: "called không khớp với if I hear.",
        d: "would call cần if ở quá khứ giả định, ví dụ if I heard.",
      },
    }),
    mcq({
      id: "c1-6",
      difficulty: "hard",
      stem: "If Nam is late again, the coach ___ him on the bench.",
      choices: { a: "leaves", b: "will leave", c: "left", d: "would leave" },
      answer: "b",
      explanation: "is late là điều kiện có thật, kết quả tương lai dùng will leave.",
      whyWrong: {
        a: "leaves có thể hiểu thành thói quen, câu này nói một lần nếu Nam lại muộn.",
        c: "left là quá khứ.",
        d: "would leave thuộc loại 2.",
      },
    }),
    mcq({
      id: "c1-7",
      difficulty: "easy",
      stem: "If you hurry now, you ___ the 7:30 train.",
      choices: { a: "catch", b: "will catch", c: "caught", d: "would catch" },
      answer: "b",
      explanation: "hurry now là điều kiện có thể xảy ra ngay, kết quả dùng will catch.",
      whyWrong: {
        a: "catch thiếu will cho kết quả tương lai gần.",
        c: "caught là quá khứ, không khớp với if you hurry.",
        d: "would catch thuộc loại 2, khi điều kiện mang tính giả định.",
      },
    }),
    mcq({
      id: "c1-8",
      difficulty: "easy",
      stem: "If Lan ___ free tomorrow morning, she will join the club meeting.",
      choices: { a: "is", b: "was", c: "were", d: "will be" },
      answer: "a",
      explanation: "tomorrow morning chỉ khả năng có thật, mệnh đề if loại 1 dùng is.",
      whyWrong: {
        b: "was đưa câu sang giả định quá khứ, trong khi vế kia là will join.",
        c: "were thuộc loại 2, không đi với will join.",
        d: "will be không đứng sau if trong câu điều kiện loại 1.",
      },
    }),
    mcq({
      id: "c1-9",
      difficulty: "medium",
      stem: "We will start the match as soon as the rain ___.",
      choices: { a: "stop", b: "stops", c: "stopped", d: "will stop" },
      answer: "b",
      explanation: "as soon as trong loại 1 dùng hiện tại đơn: the rain stops.",
      whyWrong: {
        a: "stop chưa chia cho the rain.",
        c: "stopped là quá khứ giả định, sẽ cần would start chứ không phải will start.",
        d: "will stop không đứng sau as soon as trong mẫu loại 1.",
      },
    }),
    mcq({
      id: "c1-10",
      difficulty: "medium",
      stem: "If he does not finish the essay tonight, he ___ the deadline.",
      choices: { a: "misses", b: "will miss", c: "missed", d: "would miss" },
      answer: "b",
      explanation: "does not finish tonight là điều kiện có thật, kết quả dùng will miss.",
      whyWrong: {
        a: "misses nghe như thói quen, trong khi tonight và deadline là một lần cụ thể.",
        c: "missed là quá khứ.",
        d: "would miss thuộc loại 2, cần if he did not finish.",
      },
    }),
    mcq({
      id: "c1-11",
      difficulty: "hard",
      stem: "If it ___ heavily tomorrow, the school picnic will be cancelled.",
      choices: { a: "rains", b: "will rain", c: "rained", d: "would rain" },
      answer: "a",
      explanation: "Mệnh đề if loại 1 dùng hiện tại đơn: rains, không dùng will.",
      whyWrong: {
        b: "will rain là lỗi phổ biến; if của loại 1 không mang will.",
        c: "rained đưa điều kiện sang loại 2, trong khi picnic will be cancelled là loại 1.",
        d: "would rain thuộc giả định loại 2.",
      },
    }),
    mcq({
      id: "c1-12",
      difficulty: "hard",
      stem: "You will feel better if you ___ more water during the match today.",
      choices: { a: "drink", b: "drank", c: "will drink", d: "would drink" },
      answer: "a",
      explanation: "will feel better ở vế kết quả, nên if dùng hiện tại đơn drink.",
      whyWrong: {
        b: "drank là dạng loại 2, sẽ cần would feel chứ không phải will feel.",
        c: "will drink không đứng trong mệnh đề if loại 1.",
        d: "would drink thuộc loại 2 và không khớp với will feel.",
      },
    }),
  ],
};
