import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const conditionalType2: TopicSeed = {
  id: "topic-conditional-2",
  slug: "conditional-type-2",
  name: "Conditional Type 2",
  gradeFrom: 10,
  gradeTo: 12,
  summary: "Giả định khác với thực tế ở hiện tại hoặc tương lai khó xảy ra.",
  purpose: "Nói điều không đúng lúc này, hoặc một tưởng tượng.",
  usage: [
    "Mệnh đề if: dùng quá khứ đơn.",
    "Mệnh đề chính: would + động từ nguyên mẫu.",
    "were: dùng cho mọi ngôi với be, theo kiểu trang trọng của bài thi.",
  ].join("\n"),
  structure: [
    "Mẫu: If + quá khứ đơn, would + V.",
    "Lưu ý: dạng quá khứ ở if không có nghĩa việc đã xảy ra trong quá khứ.",
  ].join("\n"),
  affirmativePattern: "If + chủ ngữ + V2, chủ ngữ + would + V.",
  negativePattern: "If + chủ ngữ + did not + V, chủ ngữ + would not + V.",
  questionPattern: "What would + chủ ngữ + V if + chủ ngữ + V2?",
  signalWords: ["if", "were", "would", "if I were you"],
  examples: [
    { sentence: "If I were taller, I would join the team.", note: "Thực tế tôi không cao hơn." },
    { sentence: "If she studied more, she would get better marks.", note: "studied là giả định, không phải một việc hôm qua." },
    { sentence: "If I were you, I would take the advice.", note: "were you là mẫu câu lời khuyên." },
  ],
  commonMistakes: [
    { wrong: "If I am rich, I would travel.", right: "If I were rich, I would travel.", why: "would đi với dạng quá khứ trong if, và be dùng were." },
    { wrong: "If she studied more, she will get better marks.", right: "If she studied more, she would get better marks.", why: "will thuộc loại 1. Loại 2 dùng would." },
    { wrong: "If I were you, I take the offer.", right: "If I were you, I would take the offer.", why: "Mệnh đề kết quả cần would." },
  ],
  comparisons: [
    { with: "Conditional type 1", note: "If it rains, I will stay là trời có thể mưa. If it rained, I would stay là giả định, thường khi người nói không trông đợi điều đó." },
  ],
  prerequisiteSlugs: ["past-simple"],
  questions: [
    mcq({
      id: "c2-1",
      difficulty: "easy",
      stem: "If I ___ taller, I would join the school team.",
      choices: { a: "am", b: "were", c: "will be", d: "had been" },
      answer: "b",
      explanation: "Giả định khác thực tế với be dùng were, đi cùng would.",
      whyWrong: {
        a: "am là hiện tại thật, không đi với would trong mẫu này.",
        c: "will be thuộc điều kiện có thật.",
        d: "had been là dạng của điều kiện loại 3, nói về quá khứ đã qua.",
      },
    }),
    mcq({
      id: "c2-2",
      difficulty: "easy",
      stem: "If she studied more, she ___ better marks.",
      choices: { a: "gets", b: "will get", c: "would get", d: "got" },
      answer: "c",
      explanation: "studied trong if loại 2 đi với would get.",
      whyWrong: {
        a: "gets là hiện tại đơn.",
        b: "will get thuộc loại 1, cần if she studies.",
        d: "got lặp dạng quá khứ ở cả hai vế và thiếu would.",
      },
    }),
    mcq({
      id: "c2-3",
      difficulty: "medium",
      stem: "If we ___ in Hue, we would cycle to school.",
      choices: { a: "live", b: "lived", c: "had lived", d: "will live" },
      answer: "b",
      explanation: "would cycle cho thấy giả định hiện tại, if dùng lived.",
      whyWrong: {
        a: "live là hiện tại thật, sẽ cần will chứ không phải would.",
        c: "had lived là quá khứ hoàn thành, dùng cho loại 3.",
        d: "will live không đứng trong if loại 2.",
      },
    }),
    mcq({
      id: "c2-4",
      difficulty: "medium",
      stem: "I would take that bike if it ___ cheaper.",
      choices: { a: "is", b: "were", c: "will be", d: "has been" },
      answer: "b",
      explanation: "would take là kết quả giả định, if it were cheaper.",
      whyWrong: {
        a: "is rẻ là sự thật hiện tại, không đi với would take.",
        c: "will be thuộc loại 1.",
        d: "has been là hiện tại hoàn thành, không phải dạng if của loại 2.",
      },
    }),
    mcq({
      id: "c2-5",
      difficulty: "hard",
      stem: "If I were you, I ___ the teacher's advice.",
      choices: { a: "take", b: "will take", c: "would take", d: "took" },
      answer: "c",
      explanation: "If I were you luôn đi với would take khi đưa lời khuyên.",
      whyWrong: {
        a: "take thiếu would.",
        b: "will take không đi với were.",
        d: "took không phải mệnh đề kết quả của câu này.",
      },
    }),
    mcq({
      id: "c2-6",
      difficulty: "hard",
      stem: "What ___ you do if you missed the last train?",
      choices: { a: "will", b: "would", c: "do", d: "did" },
      answer: "b",
      explanation: "missed ở đây là giả định, câu hỏi dùng would you do.",
      whyWrong: {
        a: "will you do cần if you miss, không phải missed.",
        c: "do không đủ để tạo What would you do.",
        d: "did you do hỏi một việc đã xảy ra, không phải giả định.",
      },
    }),
    mcq({
      id: "c2-7",
      difficulty: "easy",
      stem: "If he ___ more free time, he would learn the guitar.",
      choices: { a: "has", b: "had", c: "will have", d: "have" },
      answer: "b",
      explanation: "would learn báo hiệu giả định hiện tại, if dùng had.",
      whyWrong: {
        a: "has là hiện tại thật, sẽ đi với will learn chứ không phải would learn.",
        c: "will have không đứng trong if loại 2.",
        d: "have chưa chia và cũng không phải dạng quá khứ giả định cần thiết.",
      },
    }),
    mcq({
      id: "c2-8",
      difficulty: "easy",
      stem: "They would buy a bigger flat if they ___ richer.",
      choices: { a: "are", b: "were", c: "will be", d: "have been" },
      answer: "b",
      explanation: "would buy là kết quả giả định, if với be dùng were.",
      whyWrong: {
        a: "are giàu là sự thật hiện tại, không đi với would buy trong mẫu này.",
        c: "will be thuộc điều kiện có thật loại 1.",
        d: "have been là hiện tại hoàn thành, không phải dạng if loại 2.",
      },
    }),
    mcq({
      id: "c2-9",
      difficulty: "medium",
      stem: "She would call you tonight if she ___ your number.",
      choices: { a: "knows", b: "knew", c: "will know", d: "has known" },
      answer: "b",
      explanation: "would call cho thấy giả định, if dùng knew dù nói về tonight.",
      whyWrong: {
        a: "knows là hiện tại thật, sẽ cần will call chứ không phải would call.",
        c: "will know không đứng trong if loại 2.",
        d: "has known là hiện tại hoàn thành, không tạo điều kiện loại 2.",
      },
    }),
    mcq({
      id: "c2-10",
      difficulty: "medium",
      stem: "If this street ___ quieter, we would study near the window.",
      choices: { a: "is", b: "were", c: "will be", d: "has been" },
      answer: "b",
      explanation: "would study là giả định khác thực tế, if this street were quieter.",
      whyWrong: {
        a: "is yên tĩnh mô tả sự thật, không đi với would study.",
        c: "will be thuộc loại 1.",
        d: "has been không phải dạng if của loại 2.",
      },
    }),
    mcq({
      id: "c2-11",
      difficulty: "hard",
      stem: "If I spoke French well, I ___ apply for that internship in Lyon.",
      choices: { a: "will", b: "would", c: "can", d: "am going to" },
      answer: "b",
      explanation: "spoke là quá khứ giả định loại 2, kết quả dùng would apply.",
      whyWrong: {
        a: "will apply thuộc loại 1, cần if I speak.",
        c: "can apply thiếu would; trong mẫu loại 2 chuẩn bài thi dùng would.",
        d: "am going to apply nói kế hoạch thật, không khớp với if I spoke.",
      },
    }),
    mcq({
      id: "c2-12",
      difficulty: "hard",
      stem: "Would you accept the offer if the company ___ you a higher salary?",
      choices: { a: "offers", b: "offered", c: "will offer", d: "has offered" },
      answer: "b",
      explanation: "Would you accept là câu hỏi loại 2, if dùng offered.",
      whyWrong: {
        a: "offers là hiện tại, sẽ đi với Will you accept if the company offers.",
        c: "will offer không đứng trong if loại 2.",
        d: "has offered là hiện tại hoàn thành, không tạo giả định loại 2.",
      },
    }),
  ],
};
