import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const conjunctionsLinkingWords: TopicSeed = {
  id: "topic-conjunctions-linking-words",
  slug: "conjunctions-linking-words",
  name: "Conjunctions and Linking Words",
  gradeFrom: 10,
  gradeTo: 12,
  summary: "Nối ý theo quan hệ nguyên nhân, đối lập, kết quả, thêm ý; chú ý dấu câu với however và therefore.",
  purpose: "Ghép hai mệnh đề hoặc hai câu để bài viết mạch lạc và chọn đúng liên từ theo nghĩa.",
  usage: [
    "because, since, as: nêu nguyên nhân, đi với mệnh đề.",
    "so, therefore, as a result: nêu kết quả.",
    "although, even though, however, but: nêu đối lập.",
    "despite, in spite of: đi với danh từ hoặc V-ing, không đi với mệnh đề đầy đủ.",
    "however, therefore: thường đứng đầu câu mới, sau dấu chấm hoặc chấm phẩy, rồi có dấu phẩy.",
  ].join("\n"),
  structure: [
    "Nối mệnh đề: mệnh đề + liên từ + mệnh đề.",
    "Nối câu: Câu 1. However, / Therefore, + câu 2.",
    "despite: Despite + N / V-ing, mệnh đề.",
  ].join("\n"),
  affirmativePattern: "S + V because S + V. / Although S + V, S + V. / Despite + N, S + V.",
  negativePattern: "Although S + did not + V, S + V. / She studied hard; however, she did not pass.",
  questionPattern: "Why...? Because... / Chọn liên từ đúng nghĩa và đúng dấu câu.",
  signalWords: [
    "because",
    "although",
    "however",
    "therefore",
    "despite",
    "so",
  ],
  examples: [
    {
      sentence: "She stayed home because she had a fever.",
      note: "because nối nguyên nhân; theo sau là mệnh đề.",
    },
    {
      sentence: "Although it rained, the match continued.",
      note: "although + mệnh đề; ý chính vẫn diễn ra trái với mưa.",
    },
    {
      sentence: "He was tired. However, he finished the report.",
      note: "However mở câu mới, có dấu phẩy sau However.",
    },
  ],
  commonMistakes: [
    {
      wrong: "Despite he was ill, he went to school.",
      right: "Despite being ill, he went to school. / Although he was ill, he went to school.",
      why: "despite không đi trực tiếp với mệnh đề he was; cần N/V-ing hoặc đổi sang although.",
    },
    {
      wrong: "Although she was tired, but she kept working.",
      right: "Although she was tired, she kept working.",
      why: "Không dùng although và but cùng một cặp mệnh đề.",
    },
    {
      wrong: "He was late, however he apologised.",
      right: "He was late. However, he apologised.",
      why: "however không nối hai mệnh đề chỉ bằng một dấu phẩy như but.",
    },
  ],
  comparisons: [
    {
      with: "Although vs Despite",
      note: "Although + mệnh đề (although she was tired). Despite + danh từ/V-ing (despite her tiredness / despite being tired).",
    },
  ],
  prerequisiteSlugs: ["present-simple", "past-simple"],
  questions: [
    mcq({
      id: "clw-1",
      difficulty: "easy",
      stem: "She did not go out ___ it was raining heavily.",
      choices: { a: "so", b: "because", c: "however", d: "despite" },
      answer: "b",
      explanation: "Mệnh đề sau chỗ trống nêu nguyên nhân → because.",
      whyWrong: {
        a: "so nêu kết quả, đứng trước kết quả chứ không trước nguyên nhân.",
        c: "however nêu đối lập giữa hai câu, không thay because ở đây.",
        d: "despite cần danh từ/V-ing, không đi với it was raining trực tiếp.",
      },
    }),
    mcq({
      id: "clw-2",
      difficulty: "easy",
      stem: "___ the traffic was bad, we arrived on time.",
      choices: { a: "Because", b: "Although", c: "Therefore", d: "So" },
      answer: "b",
      explanation: "Giao thông xấu nhưng vẫn đúng giờ → quan hệ đối lập: Although.",
      whyWrong: {
        a: "Because sẽ biến giao thông xấu thành lý do đến đúng giờ, sai logic.",
        c: "Therefore nêu kết quả và thường mở câu mới có dấu phẩy.",
        d: "So cũng nêu kết quả, không mở mệnh đề đối lập kiểu này.",
      },
    }),
    mcq({
      id: "clw-3",
      difficulty: "easy",
      stem: "He studied all night, ___ he still felt unprepared.",
      choices: { a: "so", b: "because", c: "but", d: "therefore" },
      answer: "c",
      explanation: "Học cả đêm nhưng vẫn thấy chưa sẵn sàng → but nối đối lập trong một câu.",
      whyWrong: {
        a: "so mang nghĩa kết quả thuận, không khớp still felt unprepared.",
        b: "because cần đứng trước nguyên nhân, không phải đối lập.",
        d: "therefore là kết quả và thường cần dấu câu kiểu câu mới, không giống but.",
      },
    }),
    mcq({
      id: "clw-4",
      difficulty: "easy",
      stem: "It was late, ___ we took a taxi home.",
      choices: { a: "because", b: "although", c: "so", d: "despite" },
      answer: "c",
      explanation: "Muộn → kết quả bắt taxi: so.",
      whyWrong: {
        a: "because đảo quan hệ; vế sau là kết quả chứ không phải nguyên nhân.",
        b: "although là đối lập, không khớp lấy taxi vì muộn.",
        d: "despite không nối hai mệnh đề đầy đủ như vậy.",
      },
    }),
    mcq({
      id: "clw-5",
      difficulty: "medium",
      stem: "___ the heavy rain, the football match was not cancelled.",
      choices: { a: "Although", b: "Because", c: "Despite", d: "However" },
      answer: "c",
      explanation: "the heavy rain là cụm danh từ → Despite + N.",
      whyWrong: {
        a: "Although cần mệnh đề (although it rained heavily), không đi trực tiếp với the heavy rain.",
        b: "Because + N không đủ; cần because of the heavy rain, và nghĩa cũng thành nguyên nhân hủy/không hủy lệch.",
        d: "However không đứng trước cụm danh từ như giới từ.",
      },
    }),
    mcq({
      id: "clw-6",
      difficulty: "medium",
      stem: "The road was flooded. ___, the bus could not reach the village.",
      choices: { a: "Although", b: "However", c: "Therefore", d: "Despite" },
      answer: "c",
      explanation: "Câu sau là kết quả của đường ngập → Therefore, có dấu phẩy.",
      whyWrong: {
        a: "Although không đứng một mình mở câu kết quả kiểu này.",
        b: "However là đối lập, không phải kết quả logic của flooded.",
        d: "Despite cần N/V-ing, không đứng một mình trước dấu phẩy như liên từ câu.",
      },
    }),
    mcq({
      id: "clw-7",
      difficulty: "medium",
      stem: "She was exhausted. ___, she continued practising the piano.",
      choices: { a: "So", b: "Because", c: "However", d: "Therefore" },
      answer: "c",
      explanation: "Mệt nhưng vẫn luyện → đối lập giữa hai câu: However,",
      whyWrong: {
        a: "So thường nối trong một câu và mang nghĩa kết quả thuận.",
        b: "Because nêu nguyên nhân, không khớp ý vẫn tiếp tục trái với mệt.",
        d: "Therefore mang kết quả thuận, không phải đối lập.",
      },
    }),
    mcq({
      id: "clw-8",
      difficulty: "medium",
      stem: "He kept working ___ he had a terrible headache.",
      choices: {
        a: "because of",
        b: "even though",
        c: "therefore",
        d: "in spite of",
      },
      answer: "b",
      explanation: "he had... là mệnh đề → even though / although.",
      whyWrong: {
        a: "because of cần danh từ, và nghĩa thành nguyên nhân làm việc vì đau đầu — lệch.",
        c: "therefore không đứng giữa hai mệnh đề như liên từ phụ thuộc này.",
        d: "in spite of cần N/V-ing, không đi với he had...",
      },
    }),
    mcq({
      id: "clw-9",
      difficulty: "hard",
      stem: "Which sentence is punctuated correctly?",
      choices: {
        a: "The test was hard, however, most students passed.",
        b: "The test was hard. However, most students passed.",
        c: "The test was hard however, most students passed.",
        d: "The test was hard; however most students passed.",
      },
      answer: "b",
      explanation: "However nối ý đối lập giữa hai câu: chấm câu rồi However, + câu mới.",
      whyWrong: {
        a: "Dấu phẩy trước however (comma splice) không đủ để nối hai câu độc lập.",
        c: "Thiếu dấu câu trước however.",
        d: "Sau however cần dấu phẩy: however, most...",
      },
    }),
    mcq({
      id: "clw-10",
      difficulty: "hard",
      stem: "___ working overtime, she managed to finish the design.",
      choices: {
        a: "Although",
        b: "Because",
        c: "In spite of",
        d: "However",
      },
      answer: "c",
      explanation: "working overtime là V-ing → In spite of / Despite + V-ing.",
      whyWrong: {
        a: "Although cần mệnh đề (although she worked overtime).",
        b: "Because + V-ing không chuẩn; because of mới đi với N, và nghĩa cũng khác.",
        d: "However không đứng trước V-ing như giới từ.",
      },
    }),
    mcq({
      id: "clw-11",
      difficulty: "hard",
      stem: "Choose the best sentence.",
      choices: {
        a: "Although it was noisy, but the baby slept well.",
        b: "Although it was noisy, the baby slept well.",
        c: "Despite it was noisy, the baby slept well.",
        d: "However it was noisy, the baby slept well.",
      },
      answer: "b",
      explanation: "Although + mệnh đề, không kèm but; đây là mẫu đối lập chuẩn.",
      whyWrong: {
        a: "Lỗi lặp liên từ: although không đi cùng but.",
        c: "Despite không đi với mệnh đề it was; cần despite the noise / despite being noisy.",
        d: "However không thay although để mở mệnh đề phụ như vậy.",
      },
    }),
    mcq({
      id: "clw-12",
      difficulty: "hard",
      stem: "The factory closed last month; ___, many workers lost their jobs.",
      choices: { a: "although", b: "as a result", c: "despite", d: "even though" },
      answer: "b",
      explanation: "Sau chấm phẩy, as a result nêu hệ quả và thường có dấu phẩy sau cụm.",
      whyWrong: {
        a: "although là đối lập phụ thuộc, không phù hợp vị trí kết quả sau chấm phẩy kiểu này.",
        c: "despite cần N/V-ing, không đứng một mình làm liên kết kết quả.",
        d: "even though cũng là đối lập, không phải kết quả của việc đóng cửa.",
      },
    }),
  ],
};
