import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const countableUncountableNouns: TopicSeed = {
  id: "topic-countable-uncountable",
  slug: "countable-uncountable-nouns",
  name: "Countable and Uncountable Nouns",
  gradeFrom: 6,
  gradeTo: 12,
  summary: "Danh từ đếm được có số ít/số nhiều; danh từ không đếm được không dùng a/an hay số nhiều thông thường.",
  purpose:
    "Phân biệt danh từ có thể đếm từng đơn vị với danh từ chỉ chất, chất liệu, khái niệm trừu tượng để chọn mạo từ, lượng từ và động từ đúng.",
  usage: [
    "Countable: dùng a / an, có số nhiều, đi với many / few, these / those.",
    "Uncountable: không dùng a / an, không thêm -s thông thường, đi với much / little, this / that.",
    "Đếm bằng đơn vị: a bottle of water, two pieces of advice.",
  ].join("\n"),
  structure: [
    "Đếm được số ít: a / an + N + động từ số ít.",
    "Đếm được số nhiều: N-s + động từ số nhiều.",
    "Không đếm được: (some / much / a little) + N + động từ số ít.",
    "Không viết: advices, informations, furnitures.",
  ].join("\n"),
  affirmativePattern: "There is a book. There are three books. There is some milk.",
  negativePattern: "There isn't a pen. There aren't many chairs. There isn't much sugar.",
  questionPattern: "How many books...? How much water...?",
  signalWords: [
    "many",
    "much",
    "a few",
    "a little",
    "some",
    "a piece of",
    "a bottle of",
  ],
  examples: [
    {
      sentence: "I bought three apples and some milk.",
      note: "apples đếm được; milk không đếm được nên dùng some.",
    },
    {
      sentence: "How much sugar do you need?",
      note: "sugar không đếm được → how much.",
    },
    {
      sentence: "She gave me two pieces of advice.",
      note: "advice không đếm được; đếm bằng piece(s) of.",
    },
    {
      sentence: "There isn't much time left.",
      note: "time (thời gian) thường không đếm được → much.",
    },
  ],
  commonMistakes: [
    {
      wrong: "I need an advice.",
      right: "I need some advice. / I need a piece of advice.",
      why: "advice không đếm được, không dùng a/an trực tiếp.",
    },
    {
      wrong: "There are many furnitures in the room.",
      right: "There is a lot of furniture in the room.",
      why: "furniture không đếm được và đi với động từ số ít.",
    },
    {
      wrong: "How many money do you have?",
      right: "How much money do you have?",
      why: "money không đếm được → how much.",
    },
  ],
  comparisons: [
    {
      with: "Articles",
      note: "Countable số ít chưa xác định dùng a/an. Uncountable không dùng a/an; dùng some/the hoặc zero article khi nói chung.",
    },
  ],
  prerequisiteSlugs: ["articles"],
  questions: [
    mcq({
      id: "cun-1",
      difficulty: "easy",
      stem: "There ___ three chairs near the window.",
      choices: {
        a: "is",
        b: "are",
        c: "was",
        d: "been",
      },
      answer: "b",
      explanation: "chairs là danh từ đếm được số nhiều → are.",
      whyWrong: {
        a: "is đi với số ít hoặc không đếm được.",
        c: "was là quá khứ số ít, không khớp three chairs hiện tại.",
        d: "been cần have/has và không hoàn thành câu.",
      },
    }),
    mcq({
      id: "cun-2",
      difficulty: "easy",
      stem: "How ___ milk is left in the fridge?",
      choices: {
        a: "many",
        b: "much",
        c: "few",
        d: "a",
      },
      answer: "b",
      explanation: "milk không đếm được → how much.",
      whyWrong: {
        a: "many dùng với số nhiều đếm được.",
        c: "few dùng với số nhiều đếm được, không hỏi số lượng milk.",
        d: "a không tạo câu hỏi lượng với milk.",
      },
    }),
    mcq({
      id: "cun-3",
      difficulty: "easy",
      stem: "She bought ___ apple and ___ rice.",
      choices: {
        a: "an / some",
        b: "a / a",
        c: "an / a",
        d: "some / an",
      },
      answer: "a",
      explanation: "apple đếm được số ít → an; rice không đếm được → some.",
      whyWrong: {
        b: "a rice sai vì rice không đếm được.",
        c: "a rice vẫn sai.",
        d: "some apple kém tự nhiên khi nói một quả; an rice sai hoàn toàn.",
      },
    }),
    mcq({
      id: "cun-4",
      difficulty: "easy",
      stem: "There isn't ___ sugar in this bowl.",
      choices: {
        a: "many",
        b: "much",
        c: "a few",
        d: "several",
      },
      answer: "b",
      explanation: "sugar không đếm được trong câu phủ định → much.",
      whyWrong: {
        a: "many không đi với sugar không đếm được.",
        c: "a few dùng với số nhiều đếm được.",
        d: "several cũng chỉ số nhiều đếm được.",
      },
    }),
    mcq({
      id: "cun-5",
      difficulty: "medium",
      stem: "I need ___ useful advice about the exam.",
      choices: {
        a: "a",
        b: "an",
        c: "some",
        d: "many",
      },
      answer: "c",
      explanation: "advice không đếm được → some advice.",
      whyWrong: {
        a: "a advice sai vì advice không đếm được.",
        b: "an advice cũng sai cùng lý do.",
        d: "many cần danh từ số nhiều đếm được.",
      },
    }),
    mcq({
      id: "cun-6",
      difficulty: "medium",
      stem: "How ___ students are in your class?",
      choices: {
        a: "much",
        b: "many",
        c: "little",
        d: "a little",
      },
      answer: "b",
      explanation: "students đếm được số nhiều → how many.",
      whyWrong: {
        a: "much dùng với không đếm được.",
        c: "little dùng với không đếm được.",
        d: "a little cũng dành cho không đếm được.",
      },
    }),
    mcq({
      id: "cun-7",
      difficulty: "medium",
      stem: "We only have ___ eggs, so we cannot bake two cakes.",
      choices: {
        a: "a little",
        b: "much",
        c: "a few",
        d: "little",
      },
      answer: "c",
      explanation: "eggs đếm được số nhiều → a few.",
      whyWrong: {
        a: "a little đi với không đếm được.",
        b: "much đi với không đếm được.",
        d: "little đi với không đếm được.",
      },
    }),
    mcq({
      id: "cun-8",
      difficulty: "medium",
      stem: "The information ___ useful for our project.",
      choices: {
        a: "are",
        b: "were",
        c: "is",
        d: "have been",
      },
      answer: "c",
      explanation: "information không đếm được, động từ số ít → is.",
      whyWrong: {
        a: "are dành cho số nhiều.",
        b: "were là quá khứ số nhiều/you.",
        d: "have been số nhiều hoặc với I/you/we/they; không khớp information số ít không đếm được.",
      },
    }),
    mcq({
      id: "cun-9",
      difficulty: "hard",
      stem: "Could you give me ___ about the scholarship?",
      choices: {
        a: "an information",
        b: "some informations",
        c: "a piece of information",
        d: "many information",
      },
      answer: "c",
      explanation: "information không đếm được; đơn vị đúng là a piece of information.",
      whyWrong: {
        a: "an information sai vì không dùng a/an trực tiếp.",
        b: "informations không phải dạng số nhiều chuẩn.",
        d: "many không đi với information không đếm được.",
      },
    }),
    mcq({
      id: "cun-10",
      difficulty: "hard",
      stem: "There is too ___ traffic on this street in the morning.",
      choices: {
        a: "many",
        b: "few",
        c: "much",
        d: "several",
      },
      answer: "c",
      explanation: "traffic không đếm được → too much traffic.",
      whyWrong: {
        a: "many không đi với traffic.",
        b: "few dùng với số nhiều đếm được.",
        d: "several dùng với số nhiều đếm được.",
      },
    }),
    mcq({
      id: "cun-11",
      difficulty: "hard",
      stem: "She put ___ furniture in the new flat last week.",
      choices: {
        a: "many",
        b: "a few",
        c: "several",
        d: "some",
      },
      answer: "d",
      explanation: "furniture không đếm được → some furniture.",
      whyWrong: {
        a: "many furniture sai vì furniture không đếm được.",
        b: "a few cần số nhiều đếm được.",
        c: "several cũng cần số nhiều đếm được.",
      },
    }),
    mcq({
      id: "cun-12",
      difficulty: "hard",
      stem: "He does not have ___ time, but he still has ___ minutes before class.",
      choices: {
        a: "many / much",
        b: "much / a few",
        c: "a few / much",
        d: "many / a little",
      },
      answer: "b",
      explanation: "time (thời gian) không đếm được → much; minutes đếm được → a few.",
      whyWrong: {
        a: "many không đi với time; much không đi với minutes.",
        c: "a few không đi với time; much không đi với minutes.",
        d: "many không đi với time; a little không đi với minutes.",
      },
    }),
  ],
};
