import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const futureForms: TopicSeed = {
  id: "topic-future-forms",
  slug: "future-forms",
  name: "Future Forms",
  gradeFrom: 9,
  gradeTo: 12,
  summary: "Phân biệt will, be going to và hiện tại tiếp diễn khi nói về tương lai.",
  purpose: "Chọn đúng dạng tương lai theo quyết định tức thì, kế hoạch có bằng chứng, hoặc lịch đã sắp xếp.",
  usage: [
    "will: quyết định ngay lúc nói, hoặc dự đoán không có bằng chứng rõ.",
    "be going to: ý định có từ trước, hoặc có dấu hiệu thấy trước.",
    "Hiện tại tiếp diễn: lịch cá nhân đã sắp xếp, thường nêu thời gian và chỗ.",
  ].join("\n"),
  structure: [
    "will: will + V.",
    "be going to: am / is / are + going to + V.",
    "Lịch đã cố định: am / is / are + V-ing.",
    "Phủ định: thêm not.",
    "Câu hỏi: đảo will hoặc be lên trước chủ ngữ.",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + will + V / is going to + V / is + V-ing + thời gian tương lai.",
  negativePattern: "Chủ ngữ + will not + V / is not going to + V / is not + V-ing.",
  questionPattern: "Will + chủ ngữ + V? / Is + chủ ngữ + going to + V? / Are + chủ ngữ + V-ing?",
  signalWords: ["will", "going to", "tomorrow", "next week", "tonight", "at 7 p.m."],
  examples: [
    {
      sentence: "The phone is ringing. I will answer it.",
      note: "Quyết định ngay khi chuông reo, dùng will.",
    },
    {
      sentence: "Look at those dark clouds. It is going to rain.",
      note: "Có bằng chứng trước mắt, dùng be going to.",
    },
    {
      sentence: "We are meeting the coach at 5 p.m. tomorrow.",
      note: "Cuộc hẹn đã sắp xếp, dùng hiện tại tiếp diễn.",
    },
  ],
  commonMistakes: [
    {
      wrong: "I will visit my grandparents next Sunday. I booked the tickets last week.",
      right: "I am visiting my grandparents next Sunday. I booked the tickets last week.",
      why: "Đã đặt vé và có ngày cụ thể nên dùng lịch hiện tại tiếp diễn, không phải quyết định tức thì.",
    },
    {
      wrong: "Look at the sky. It will rain in a minute.",
      right: "Look at the sky. It is going to rain in a minute.",
      why: "Look at the sky là bằng chứng thấy được, bài tập dạng này chọn going to.",
    },
    {
      wrong: "A: The bag is heavy. B: I am going to help you.",
      right: "A: The bag is heavy. B: I will help you.",
      why: "Người B vừa nghe và quyết định giúp ngay, dùng will.",
    },
  ],
  comparisons: [
    {
      with: "Present continuous (habit vs arrangement)",
      note: "Hiện tại tiếp diễn nói việc đang xảy ra: She is cooking now. Khi có mốc tương lai rõ như tomorrow at 3, nó thường mang nghĩa lịch đã sắp xếp: She is cooking for guests tomorrow at 3.",
    },
    {
      with: "Present simple",
      note: "Hiện tại đơn với lịch công cộng (The train leaves at 6). Future forms trong bài này tập trung will, going to và lịch cá nhân am/is/are + V-ing.",
    },
  ],
  prerequisiteSlugs: ["present-simple", "present-continuous"],
  questions: [
    mcq({
      id: "ff-1",
      difficulty: "easy",
      stem: "The doorbell is ringing. I ___ the door.",
      choices: {
        a: "am answering",
        b: "will answer",
        c: "am going to answer",
        d: "answer",
      },
      answer: "b",
      explanation: "Chuông vừa reo và người nói quyết định ngay, dùng will answer.",
      whyWrong: {
        a: "am answering nghe như việc đang mở cửa, không phải quyết định tức thì.",
        c: "am going to answer gợi ý đã có kế hoạch từ trước, câu này không có ý đó.",
        d: "answer là hiện tại đơn, không diễn đạt quyết định lúc nói.",
      },
    }),
    mcq({
      id: "ff-2",
      difficulty: "easy",
      stem: "Look at those dark clouds. It ___ rain soon.",
      choices: {
        a: "will",
        b: "is going to",
        c: "is",
        d: "goes to",
      },
      answer: "b",
      explanation: "Có mây đen làm bằng chứng, dùng is going to rain.",
      whyWrong: {
        a: "will rain thiếu bằng chứng rõ; câu đã có Look at those dark clouds.",
        c: "is rain không đúng ngữ pháp.",
        d: "goes to không phải cấu trúc tương lai.",
      },
    }),
    mcq({
      id: "ff-3",
      difficulty: "easy",
      stem: "We ___ the dentist at 9 a.m. tomorrow. The appointment is already booked.",
      choices: {
        a: "see",
        b: "will see",
        c: "are seeing",
        d: "saw",
      },
      answer: "c",
      explanation: "Cuộc hẹn đã đặt, dùng hiện tại tiếp diễn are seeing cho lịch.",
      whyWrong: {
        a: "see là hiện tại đơn, không nhấn lịch cá nhân đã sắp xếp.",
        b: "will see thường là quyết định hoặc dự đoán, không khớp với appointment đã booked.",
        d: "saw là quá khứ.",
      },
    }),
    mcq({
      id: "ff-4",
      difficulty: "easy",
      stem: "I ___ a new laptop next month. I have already saved enough money.",
      choices: {
        a: "buy",
        b: "am going to buy",
        c: "bought",
        d: "am buying",
      },
      answer: "b",
      explanation: "Đã tiết kiệm đủ và có ý định trước, dùng am going to buy.",
      whyWrong: {
        a: "buy thiếu cấu trúc tương lai.",
        c: "bought là quá khứ.",
        d: "am buying thường cần lịch cụ thể hơn; câu nhấn ý định đã có sẵn nên going to rõ hơn.",
      },
    }),
    mcq({
      id: "ff-5",
      difficulty: "medium",
      stem: "A: This box is too heavy for me. B: Don't worry. I ___ you carry it.",
      choices: {
        a: "am helping",
        b: "am going to help",
        c: "will help",
        d: "help",
      },
      answer: "c",
      explanation: "B vừa nghe và đề nghị giúp ngay, dùng will help.",
      whyWrong: {
        a: "am helping nói việc đang xảy ra, không phải lời đề nghị vừa quyết định.",
        b: "am going to help gợi kế hoạch từ trước, hội thoại này là phản ứng tức thì.",
        d: "help thiếu will trong lời đề nghị dạng này.",
      },
    }),
    mcq({
      id: "ff-6",
      difficulty: "medium",
      stem: "She ___ her driving test next Friday. She has been practicing every day.",
      choices: {
        a: "takes",
        b: "is going to take",
        c: "took",
        d: "has taken",
      },
      answer: "b",
      explanation: "Có ý định và sự chuẩn bị rõ, dùng is going to take.",
      whyWrong: {
        a: "takes có thể dùng cho lịch công cộng, nhưng câu nhấn sự chuẩn bị cá nhân nên going to phù hợp hơn trong bài này.",
        c: "took là quá khứ.",
        d: "has taken là hiện tại hoàn thành, việc chưa xảy ra.",
      },
    }),
    mcq({
      id: "ff-7",
      difficulty: "medium",
      stem: "They ___ to Da Nang this Saturday. Their flight tickets are on the table.",
      choices: {
        a: "fly",
        b: "will fly",
        c: "are flying",
        d: "flew",
      },
      answer: "c",
      explanation: "Đã có vé và ngày cụ thể, dùng are flying cho lịch đã sắp xếp.",
      whyWrong: {
        a: "fly là hiện tại đơn, không nhấn lịch đã cố định trong ngữ cảnh này.",
        b: "will fly nghe như quyết định hoặc dự đoán, trong khi vé đã sẵn.",
        d: "flew là quá khứ.",
      },
    }),
    mcq({
      id: "ff-8",
      difficulty: "medium",
      stem: "I think our team ___ the match, but I am not sure.",
      choices: {
        a: "wins",
        b: "is winning",
        c: "will win",
        d: "won",
      },
      answer: "c",
      explanation: "I think và không chắc là dự đoán không có bằng chứng cứng, dùng will win.",
      whyWrong: {
        a: "wins là hiện tại đơn, không diễn đạt dự đoán tương lai kiểu này.",
        b: "is winning nói việc đang thắng, không phải dự đoán trận chưa đá.",
        d: "won là quá khứ.",
      },
    }),
    mcq({
      id: "ff-9",
      difficulty: "hard",
      stem: "Careful! That glass is near the edge. It ___ fall.",
      choices: {
        a: "will",
        b: "is going to",
        c: "is",
        d: "goes to",
      },
      answer: "b",
      explanation: "Tình huống sắp xảy ra có dấu hiệu thấy được, dùng is going to fall.",
      whyWrong: {
        a: "will fall thiếu cảm giác bằng chứng ngay trước mắt mà câu đang mô tả.",
        c: "is fall sai ngữ pháp.",
        d: "goes to không phải cấu trúc be going to.",
      },
    }),
    mcq({
      id: "ff-10",
      difficulty: "hard",
      stem: "___ you ___ to the cinema with us tonight? We already bought three tickets.",
      choices: {
        a: "Will / come",
        b: "Are / coming",
        c: "Do / come",
        d: "Did / come",
      },
      answer: "b",
      explanation: "Đã mua vé và hỏi lịch tối nay, dùng Are you coming.",
      whyWrong: {
        a: "Will you come nghe như lời mời mở, trong khi vé đã mua và hỏi về lịch đã sắp.",
        c: "Do you come là hiện tại đơn thói quen.",
        d: "Did you come là quá khứ.",
      },
    }),
    mcq({
      id: "ff-11",
      difficulty: "hard",
      stem: "I have decided: from next Monday I ___ wake up at 5 every day.",
      choices: {
        a: "wake",
        b: "am waking",
        c: "am going to wake",
        d: "woke",
      },
      answer: "c",
      explanation: "I have decided báo ý định đã chốt trước lúc nói, dùng am going to wake.",
      whyWrong: {
        a: "wake thiếu cấu trúc tương lai.",
        b: "am waking thường cho lịch một lần cụ thể, không khớp thói quen sẽ bắt đầu từ Monday.",
        d: "woke là quá khứ.",
      },
    }),
    mcq({
      id: "ff-12",
      difficulty: "hard",
      stem: "A: We have no bread left. B: Okay, I ___ some on my way home.",
      choices: {
        a: "am buying",
        b: "am going to buy",
        c: "will buy",
        d: "buy",
      },
      answer: "c",
      explanation: "Okay cho thấy B vừa quyết định ngay trong hội thoại, dùng will buy.",
      whyWrong: {
        a: "am buying gợi lịch đã sắp từ trước, không khớp phản ứng Okay.",
        b: "am going to buy cũng gợi kế hoạch sẵn, trong khi đây là quyết định tức thì.",
        d: "buy thiếu will.",
      },
    }),
  ],
};
