import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const gerundInfinitive: TopicSeed = {
  id: "topic-gerund-infinitive",
  slug: "gerund-infinitive",
  name: "Gerund and Infinitive",
  gradeFrom: 10,
  gradeTo: 12,
  summary: "Động từ theo sau bằng V-ing hoặc to + V theo mẫu cố định.",
  purpose: "Chọn đúng dạng sau enjoy, avoid, decide, want, stop và một số mẫu phổ biến trong đề.",
  usage: [
    "enjoy, finish, avoid, mind, suggest: + V-ing.",
    "decide, hope, want, plan, promise, refuse: + to V.",
    "stop + V-ing: ngừng việc đó.",
    "stop + to V: dừng lại để làm việc khác.",
    "remember / forget + to V: việc cần làm.",
    "remember / forget + V-ing: việc đã xảy ra (chỉ dùng khi ngữ cảnh rõ).",
  ].join("\n"),
  structure: [
    "Gerund: động từ chính + V-ing.",
    "Infinitive: động từ chính + to + V.",
    "V-ing làm chủ ngữ: có thể đứng đầu câu.",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + enjoy/avoid + V-ing. Chủ ngữ + decide/want + to V.",
  negativePattern: "Chủ ngữ + do/does not + want + to V. Chủ ngữ + avoid + not + V-ing ít dùng; thường dùng avoid + V-ing.",
  questionPattern: "Do/Does + chủ ngữ + enjoy + V-ing? / Did + chủ ngữ + decide + to V?",
  signalWords: ["enjoy", "avoid", "decide", "want", "stop", "promise"],
  examples: [
    {
      sentence: "She enjoys reading novels before bed.",
      note: "enjoy + V-ing.",
    },
    {
      sentence: "They decided to stay at home.",
      note: "decide + to V.",
    },
    {
      sentence: "He stopped talking when the teacher entered.",
      note: "stopped talking = ngừng nói.",
    },
  ],
  commonMistakes: [
    {
      wrong: "She enjoys to read novels.",
      right: "She enjoys reading novels.",
      why: "enjoy đi với V-ing, không với to V.",
    },
    {
      wrong: "They decided staying at home.",
      right: "They decided to stay at home.",
      why: "decide đi với to V.",
    },
    {
      wrong: "He stopped to talk when the teacher entered. (nghĩa muốn nói ngừng nói)",
      right: "He stopped talking when the teacher entered.",
      why: "stop + V-ing = ngừng hành động đó; stop + to V = dừng lại để làm việc khác.",
    },
  ],
  comparisons: [
    {
      with: "stop + V-ing vs stop + to V",
      note: "She stopped smoking = cô ấy bỏ hút. She stopped to smoke = cô ấy dừng lại (ví dụ đang đi) để hút một điếu.",
    },
    {
      with: "Present simple patterns",
      note: "Thì vẫn chia ở động từ chính: She enjoys / They decide. Dạng sau đó cố định là V-ing hoặc to V, không chia thì.",
    },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "gi-1",
      difficulty: "easy",
      stem: "My sister enjoys ___ badminton on weekends.",
      choices: {
        a: "play",
        b: "to play",
        c: "playing",
        d: "played",
      },
      answer: "c",
      explanation: "enjoy + V-ing: enjoying playing.",
      whyWrong: {
        a: "play là nguyên mẫu không to, không đứng sau enjoy.",
        b: "to play sai vì enjoy không lấy to V.",
        d: "played là quá khứ/phân từ, không phải gerund sau enjoy.",
      },
    }),
    mcq({
      id: "gi-2",
      difficulty: "easy",
      stem: "We decided ___ early for the exam.",
      choices: {
        a: "leaving",
        b: "to leave",
        c: "leave",
        d: "left",
      },
      answer: "b",
      explanation: "decide + to V: decided to leave.",
      whyWrong: {
        a: "leaving là gerund; decide không lấy V-ing.",
        c: "leave thiếu to.",
        d: "left là quá khứ.",
      },
    }),
    mcq({
      id: "gi-3",
      difficulty: "easy",
      stem: "Please avoid ___ noise in the library.",
      choices: {
        a: "make",
        b: "to make",
        c: "making",
        d: "made",
      },
      answer: "c",
      explanation: "avoid + V-ing: avoid making.",
      whyWrong: {
        a: "make không đúng sau avoid.",
        b: "to make sai mẫu avoid.",
        d: "made không phải gerund.",
      },
    }),
    mcq({
      id: "gi-4",
      difficulty: "easy",
      stem: "Nam wants ___ a scholarship next year.",
      choices: {
        a: "getting",
        b: "to get",
        c: "get",
        d: "got",
      },
      answer: "b",
      explanation: "want + to V: wants to get.",
      whyWrong: {
        a: "getting là gerund; want thường lấy to V.",
        c: "get thiếu to.",
        d: "got là quá khứ.",
      },
    }),
    mcq({
      id: "gi-5",
      difficulty: "medium",
      stem: "Would you mind ___ the window? It is hot in here.",
      choices: {
        a: "open",
        b: "to open",
        c: "opening",
        d: "opened",
      },
      answer: "c",
      explanation: "mind + V-ing: mind opening.",
      whyWrong: {
        a: "open không đứng sau mind trong mẫu này.",
        b: "to open sai vì mind lấy gerund.",
        d: "opened không phải gerund.",
      },
    }),
    mcq({
      id: "gi-6",
      difficulty: "medium",
      stem: "She promised ___ me after the meeting.",
      choices: {
        a: "calling",
        b: "to call",
        c: "call",
        d: "called",
      },
      answer: "b",
      explanation: "promise + to V: promised to call.",
      whyWrong: {
        a: "calling sai mẫu promise.",
        c: "call thiếu to.",
        d: "called là quá khứ.",
      },
    }),
    mcq({
      id: "gi-7",
      difficulty: "medium",
      stem: "The students finished ___ their posters before noon.",
      choices: {
        a: "make",
        b: "to make",
        c: "making",
        d: "made",
      },
      answer: "c",
      explanation: "finish + V-ing: finished making.",
      whyWrong: {
        a: "make không đúng sau finish.",
        b: "to make sai mẫu finish.",
        d: "made ở đây không thay cho gerund sau finish.",
      },
    }),
    mcq({
      id: "gi-8",
      difficulty: "medium",
      stem: "He refused ___ the unfair contract.",
      choices: {
        a: "signing",
        b: "to sign",
        c: "sign",
        d: "signed",
      },
      answer: "b",
      explanation: "refuse + to V: refused to sign.",
      whyWrong: {
        a: "signing sai mẫu refuse.",
        c: "sign thiếu to.",
        d: "signed là quá khứ.",
      },
    }),
    mcq({
      id: "gi-9",
      difficulty: "hard",
      stem: "She was tired, so she stopped ___ and had a short rest.",
      choices: {
        a: "to work",
        b: "working",
        c: "work",
        d: "worked",
      },
      answer: "b",
      explanation: "Ngừng làm việc rồi nghỉ: stopped working.",
      whyWrong: {
        a: "stopped to work nghĩa dừng lại để bắt đầu làm việc, trái với had a short rest.",
        c: "work thiếu -ing sau stop với nghĩa ngừng việc.",
        d: "worked không đúng sau stop trong mẫu này.",
      },
    }),
    mcq({
      id: "gi-10",
      difficulty: "hard",
      stem: "On the way home, he stopped ___ some water at a shop.",
      choices: {
        a: "buying",
        b: "to buy",
        c: "buy",
        d: "bought",
      },
      answer: "b",
      explanation: "Dừng lại trên đường để mua nước: stopped to buy.",
      whyWrong: {
        a: "stopped buying nghĩa ngừng việc mua (bỏ thói quen mua), không khớp On the way home.",
        c: "buy thiếu to.",
        d: "bought không đúng sau stop trong mẫu mục đích.",
      },
    }),
    mcq({
      id: "gi-11",
      difficulty: "hard",
      stem: "Don't forget ___ your ID card tomorrow. You will need it at the gate.",
      choices: {
        a: "bringing",
        b: "to bring",
        c: "bring",
        d: "brought",
      },
      answer: "b",
      explanation: "Việc cần làm trong tương lai: forget + to bring.",
      whyWrong: {
        a: "forget bringing thường nói việc đã mang trong quá khứ, không khớp tomorrow.",
        c: "bring thiếu to.",
        d: "brought là quá khứ.",
      },
    }),
    mcq({
      id: "gi-12",
      difficulty: "hard",
      stem: "The teacher suggested ___ the essay into three clear parts.",
      choices: {
        a: "divide",
        b: "to divide",
        c: "dividing",
        d: "divided",
      },
      answer: "c",
      explanation: "suggest + V-ing: suggested dividing.",
      whyWrong: {
        a: "divide không đúng sau suggest trong mẫu chuẩn bài tập này.",
        b: "to divide không phải mẫu suggest + V-ing (tránh lẫn với suggest that...).",
        d: "divided là quá khứ/phân từ.",
      },
    }),
  ],
};
