import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const modalsObligationPossibility: TopicSeed = {
  id: "topic-modals-obligation-possibility",
  slug: "modals-obligation-possibility",
  name: "Modals: Obligation and Possibility",
  gradeFrom: 9,
  gradeTo: 12,
  summary: "must, have to cho bắt buộc; might cho khả năng không chắc.",
  purpose: "Phân biệt nghĩa vụ mạnh, nghĩa vụ từ quy định bên ngoài, và phỏng đoán yếu.",
  usage: [
    "must: nghĩa vụ người nói thấy cần thiết, hoặc quy tắc nội bộ mạnh.",
    "have to: quy định, lịch trình, hoặc hoàn cảnh bên ngoài.",
    "might + V: khả năng thấp hoặc không chắc.",
    "must not: cấm.",
    "do not have to: không bắt buộc.",
  ].join("\n"),
  structure: [
    "Khẳng định: must + V; have / has to + V; might + V.",
    "Phủ định: must not + V; do / does not have to + V; might not + V.",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + must/have to/might + động từ nguyên mẫu.",
  negativePattern: "Chủ ngữ + must not + V / do not have to + V / might not + V.",
  questionPattern: "Must + chủ ngữ + V? / Do + chủ ngữ + have to + V? / Might + chủ ngữ + V?",
  signalWords: ["must", "have to", "has to", "might", "must not", "don't have to"],
  examples: [
    {
      sentence: "You must wear a helmet on this site. It is the company rule.",
      note: "must nhấn quy tắc bắt buộc mạnh.",
    },
    {
      sentence: "She has to catch the 6 a.m. bus because school starts early.",
      note: "has to đến từ hoàn cảnh bên ngoài (giờ học).",
    },
    {
      sentence: "He might be at the library, but I am not sure.",
      note: "might = khả năng, không chắc chắn.",
    },
  ],
  commonMistakes: [
    {
      wrong: "You don't have to smoke here. It is forbidden.",
      right: "You must not smoke here. It is forbidden.",
      why: "Cấm dùng must not. don't have to chỉ nghĩa không bắt buộc.",
    },
    {
      wrong: "She must to finish the form today.",
      right: "She must finish the form today.",
      why: "Sau must dùng nguyên mẫu không to.",
    },
    {
      wrong: "He mights be late.",
      right: "He might be late.",
      why: "might không thêm -s theo chủ ngữ.",
    },
  ],
  comparisons: [
    {
      with: "must vs have to",
      note: "Trong bài tập này: must = người nói/quy tắc nhấn mạnh sự cần thiết; have to = áp lực từ bên ngoài (luật, lịch, hoàn cảnh). Phủ định khác hẳn: must not = cấm; don't have to = không cần.",
    },
    {
      with: "might vs must (deduction)",
      note: "might = có thể, không chắc. Bài này không dùng must theo nghĩa suy luận chắc chắn (He must be tired), chỉ dùng must cho nghĩa vụ.",
    },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "mop-1",
      difficulty: "easy",
      stem: "In this lab, students ___ wear safety glasses. It is a strict rule.",
      choices: {
        a: "might",
        b: "must",
        c: "don't have to",
        d: "maybe",
      },
      answer: "b",
      explanation: "strict rule đòi hỏi bắt buộc mạnh: must wear.",
      whyWrong: {
        a: "might chỉ khả năng, không phải quy tắc bắt buộc.",
        c: "don't have to nghĩa là không bắt buộc.",
        d: "maybe không phải động từ khiếm khuyết đứng trước wear.",
      },
    }),
    mcq({
      id: "mop-2",
      difficulty: "easy",
      stem: "I ___ leave now. My bus leaves in ten minutes.",
      choices: {
        a: "might",
        b: "have to",
        c: "must not",
        d: "don't have to",
      },
      answer: "b",
      explanation: "Giờ xe buýt là hoàn cảnh bên ngoài, dùng have to leave.",
      whyWrong: {
        a: "might leave chỉ là có thể rời, không khớp xe sắp chạy.",
        c: "must not leave là cấm rời đi.",
        d: "don't have to leave nghĩa không cần đi.",
      },
    }),
    mcq({
      id: "mop-3",
      difficulty: "easy",
      stem: "Linh isn't at home. She ___ be at the sports club, but I'm not sure.",
      choices: {
        a: "must",
        b: "has to",
        c: "might",
        d: "mustn't",
      },
      answer: "c",
      explanation: "I'm not sure báo khả năng thấp: might be.",
      whyWrong: {
        a: "must ở đây dễ hiểu thành suy luận chắc, câu đã nói không chắc.",
        b: "has to be mang nghĩa bắt buộc, không phải phỏng đoán.",
        d: "mustn't be là cấm hoặc không được phép.",
      },
    }),
    mcq({
      id: "mop-4",
      difficulty: "easy",
      stem: "You ___ bring a gift. Coming to the party is enough.",
      choices: {
        a: "must",
        b: "have to",
        c: "don't have to",
        d: "must not",
      },
      answer: "c",
      explanation: "Coming is enough nghĩa quà không bắt buộc: don't have to bring.",
      whyWrong: {
        a: "must bring là bắt buộc mang quà.",
        b: "have to bring cũng là bắt buộc.",
        d: "must not bring là cấm mang quà.",
      },
    }),
    mcq({
      id: "mop-5",
      difficulty: "medium",
      stem: "You ___ use your phone during the exam. If you do, you will be disqualified.",
      choices: {
        a: "don't have to",
        b: "might",
        c: "must not",
        d: "have to",
      },
      answer: "c",
      explanation: "Bị loại nếu dùng điện thoại = hành vi bị cấm: must not use.",
      whyWrong: {
        a: "don't have to use nghĩa không bắt buộc dùng, không phải cấm.",
        b: "might use chỉ khả năng.",
        d: "have to use nghĩa bắt buộc phải dùng.",
      },
    }),
    mcq({
      id: "mop-6",
      difficulty: "medium",
      stem: "Staff members ___ arrive before 7:30. The manager checks the attendance list.",
      choices: {
        a: "might",
        b: "have to",
        c: "don't have to",
        d: "maybe",
      },
      answer: "b",
      explanation: "Điểm danh và giờ quy định là áp lực bên ngoài: have to arrive.",
      whyWrong: {
        a: "might arrive không phải quy định.",
        c: "don't have to arrive trái với việc bị kiểm tra chuyên cần.",
        d: "maybe không đứng trước arrive như modal.",
      },
    }),
    mcq({
      id: "mop-7",
      difficulty: "medium",
      stem: "The lights are off. Someone ___ still be inside, or the room may be empty.",
      choices: {
        a: "must",
        b: "has to",
        c: "might",
        d: "mustn't",
      },
      answer: "c",
      explanation: "or the room may be empty cho thấy không chắc: might still be.",
      whyWrong: {
        a: "must still be nghe chắc chắn quá so với vế or may be empty.",
        b: "has to be mang nghĩa bắt buộc/khách quan chắc, không khớp sự lưỡng lự.",
        d: "mustn't be là cấm ở bên trong.",
      },
    }),
    mcq({
      id: "mop-8",
      difficulty: "medium",
      stem: "Tomorrow is a public holiday, so we ___ go to school.",
      choices: {
        a: "must",
        b: "have to",
        c: "don't have to",
        d: "must not",
      },
      answer: "c",
      explanation: "Ngày nghỉ nghĩa không bắt buộc đến trường: don't have to go.",
      whyWrong: {
        a: "must go là bắt buộc đi học.",
        b: "have to go cũng là bắt buộc.",
        d: "must not go là bị cấm đến trường, mạnh hơn chỉ là ngày nghỉ.",
      },
    }),
    mcq({
      id: "mop-9",
      difficulty: "hard",
      stem: "I ___ finish this report tonight. I promised the teacher I would.",
      choices: {
        a: "might",
        b: "must",
        c: "don't have to",
        d: "mustn't",
      },
      answer: "b",
      explanation: "Lời hứa tạo nghĩa vụ người nói tự cảm thấy: must finish.",
      whyWrong: {
        a: "might finish chỉ là có thể hoàn thành.",
        c: "don't have to finish trái với lời hứa.",
        d: "mustn't finish là cấm hoàn thành.",
      },
    }),
    mcq({
      id: "mop-10",
      difficulty: "hard",
      stem: "Applicants ___ submit the form by Friday. Late forms are not accepted.",
      choices: {
        a: "might",
        b: "have to",
        c: "don't have to",
        d: "mustn't",
      },
      answer: "b",
      explanation: "Hạn nộp và hậu quả từ quy định bên ngoài: have to submit.",
      whyWrong: {
        a: "might submit không khớp late forms are not accepted.",
        c: "don't have to submit trái với hạn cứng.",
        d: "mustn't submit là cấm nộp.",
      },
    }),
    mcq({
      id: "mop-11",
      difficulty: "hard",
      stem: "Take an umbrella. It ___ rain later, though the sky looks mixed.",
      choices: {
        a: "must",
        b: "has to",
        c: "might",
        d: "mustn't",
      },
      answer: "c",
      explanation: "sky looks mixed và lời khuyên mang ô = khả năng mưa không chắc: might rain.",
      whyWrong: {
        a: "must rain nghe quá chắc so với mixed sky.",
        b: "has to rain mang nghĩa buộc phải mưa, không phải dự báo khả năng.",
        d: "mustn't rain là cấm mưa, vô nghĩa ở đây.",
      },
    }),
    mcq({
      id: "mop-12",
      difficulty: "hard",
      stem: "You ___ tell anyone this password. Sharing it is against the rules.",
      choices: {
        a: "don't have to",
        b: "might",
        c: "must not",
        d: "have to",
      },
      answer: "c",
      explanation: "against the rules = bị cấm tiết lộ: must not tell.",
      whyWrong: {
        a: "don't have to tell chỉ nghĩa không bắt buộc nói, vẫn có thể nói.",
        b: "might tell chỉ khả năng.",
        d: "have to tell nghĩa bắt buộc phải nói.",
      },
    }),
  ],
};
