import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const modalsCanCouldShould: TopicSeed = {
  id: "topic-modals-can-could-should",
  slug: "modals-can-could-should",
  name: "Modals: can, could, should",
  gradeFrom: 7,
  gradeTo: 12,
  summary: "Động từ khuyết thiếu can, could, should để nói khả năng, xin phép và lời khuyên.",
  purpose: "Diễn tả biết làm gì, xin phép lịch sự, khả năng trong quá khứ, hoặc nên làm gì.",
  usage: [
    "can: khả năng hiện tại, hoặc xin phép thân mật.",
    "could: quá khứ của can, hoặc xin phép lịch sự hơn.",
    "should: lời khuyên hoặc việc nên làm.",
  ].join("\n"),
  structure: [
    "Khẳng định: modal + động từ nguyên mẫu không to.",
    "Phủ định: cannot / can't, could not / couldn't, should not / shouldn't.",
    "Câu hỏi: đảo modal lên trước chủ ngữ.",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + can/could/should + V.",
  negativePattern: "Chủ ngữ + cannot/could not/should not + V.",
  questionPattern: "Can/Could/Should + chủ ngữ + V?",
  signalWords: ["can", "could", "should", "can't", "shouldn't", "able to"],
  examples: [
    {
      sentence: "She can swim very well.",
      note: "can nói khả năng hiện tại; swim không có to.",
    },
    {
      sentence: "Could you open the window, please?",
      note: "could xin phép hoặc yêu cầu lịch sự.",
    },
    {
      sentence: "You should sleep earlier before the exam.",
      note: "should đưa lời khuyên.",
    },
  ],
  commonMistakes: [
    {
      wrong: "She can to swim.",
      right: "She can swim.",
      why: "Sau modal không dùng to trước động từ chính.",
    },
    {
      wrong: "He cans speak English.",
      right: "He can speak English.",
      why: "Modal không thêm -s theo ngôi thứ ba.",
    },
    {
      wrong: "You should to revise Unit 5.",
      right: "You should revise Unit 5.",
      why: "should + nguyên mẫu không to.",
    },
  ],
  comparisons: [
    {
      with: "Can vs could",
      note: "can thường là khả năng hoặc xin phép hiện tại. could là quá khứ của can, hoặc lời xin phép/gợi ý lịch sự hơn.",
    },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "mccs-1",
      difficulty: "easy",
      stem: "My brother ___ play the guitar quite well.",
      choices: { a: "can", b: "cans", c: "can to", d: "should to" },
      answer: "a",
      explanation: "Khả năng hiện tại dùng can + nguyên mẫu.",
      whyWrong: {
        b: "can không thêm -s.",
        c: "can không đi với to.",
        d: "should to sai hình thái; câu này cũng nói khả năng chứ không phải lời khuyên.",
      },
    }),
    mcq({
      id: "mccs-2",
      difficulty: "easy",
      stem: "___ I borrow your dictionary for a minute?",
      choices: { a: "Do", b: "Can", c: "Should", d: "Am" },
      answer: "b",
      explanation: "Xin phép thân mật dùng Can I ...?",
      whyWrong: {
        a: "Do I borrow không phải cách xin phép chuẩn.",
        c: "Should I borrow thiên về hỏi có nên mượn không, không phải xin phép thông thường.",
        d: "Am I borrow sai ngữ pháp.",
      },
    }),
    mcq({
      id: "mccs-3",
      difficulty: "easy",
      stem: "You ___ drink more water when you have a fever.",
      choices: { a: "can to", b: "should", c: "should to", d: "coulds" },
      answer: "b",
      explanation: "Lời khuyên dùng should + nguyên mẫu.",
      whyWrong: {
        a: "can to sai; can cũng không mang nghĩa khuyên bằng should.",
        c: "should không đi với to.",
        d: "coulds không tồn tại.",
      },
    }),
    mcq({
      id: "mccs-4",
      difficulty: "easy",
      stem: "I'm sorry, I ___ hear you clearly. The line is bad.",
      choices: { a: "can", b: "can't", c: "should", d: "shouldn't" },
      answer: "b",
      explanation: "Không nghe được → phủ định khả năng: can't.",
      whyWrong: {
        a: "can khẳng định nghe được, trái với I'm sorry.",
        c: "should là lời khuyên, không nói khả năng nghe.",
        d: "shouldn't là không nên, không khớp nghĩa nghe điện thoại.",
      },
    }),
    mcq({
      id: "mccs-5",
      difficulty: "medium",
      stem: "When I was six, I ___ ride a bike without help.",
      choices: { a: "can", b: "could", c: "should", d: "can't" },
      answer: "b",
      explanation: "Khả năng trong quá khứ dùng could.",
      whyWrong: {
        a: "can là hiện tại, trong khi when I was six đã qua.",
        c: "should là lời khuyên, không kể khả năng lúc nhỏ.",
        d: "can't phủ định hiện tại, không khớp câu khẳng định quá khứ.",
      },
    }),
    mcq({
      id: "mccs-6",
      difficulty: "medium",
      stem: "___ you help me with this heavy box, please?",
      choices: { a: "Should", b: "Could", c: "Do", d: "Must" },
      answer: "b",
      explanation: "Yêu cầu lịch sự dùng Could you ...?",
      whyWrong: {
        a: "Should you help nghe như hỏi có nên giúp không, không phải lời nhờ lịch sự.",
        c: "Do you help không mang sắc thái nhờ việc ngay lúc nói.",
        d: "Must mang nghĩa bắt buộc, không phải lời nhờ lịch sự.",
      },
    }),
    mcq({
      id: "mccs-7",
      difficulty: "medium",
      stem: "Students ___ talk during the listening test.",
      choices: {
        a: "shouldn't",
        b: "shouldn't to",
        c: "can't to",
        d: "could not to",
      },
      answer: "a",
      explanation: "Không nên nói chuyện → shouldn't + talk.",
      whyWrong: {
        b: "shouldn't không đi với to.",
        c: "can't to sai hình thái.",
        d: "could not to vừa sai to vừa không phải lời khuyên chuẩn ở đây.",
      },
    }),
    mcq({
      id: "mccs-8",
      difficulty: "medium",
      stem: "If you feel tired, you ___ take a short break.",
      choices: { a: "can", b: "should", c: "could to", d: "cans" },
      answer: "b",
      explanation: "Trong ngữ cảnh lời khuyên sức khỏe, should là đáp án chắc nhất.",
      whyWrong: {
        a: "can chỉ khả năng nghỉ được, yếu hơn lời khuyên should.",
        c: "could to sai vì có to.",
        d: "cans không tồn tại.",
      },
    }),
    mcq({
      id: "mccs-9",
      difficulty: "hard",
      stem: "She ___ speak French when she lived in Paris, but she ___ remember much now.",
      choices: {
        a: "can / can't",
        b: "could / can't",
        c: "should / couldn't",
        d: "could / shouldn't",
      },
      answer: "b",
      explanation: "Quá khứ dùng could; hiện tại không nhớ nhiều dùng can't.",
      whyWrong: {
        a: "can không khớp when she lived in Paris.",
        c: "should không kể khả năng ngôn ngữ trong quá khứ.",
        d: "shouldn't nói không nên, không phải không nhớ được.",
      },
    }),
    mcq({
      id: "mccs-10",
      difficulty: "hard",
      stem: "You look pale. I think you ___ see a doctor this afternoon.",
      choices: {
        a: "can",
        b: "could",
        c: "should",
        d: "shouldn't",
      },
      answer: "c",
      explanation: "Nhìn xanh xao → lời khuyên mạnh: should see a doctor.",
      whyWrong: {
        a: "can chỉ khả năng đi khám, không nhấn mạnh lời khuyên.",
        b: "could mềm hơn và thiên gợi ý khả năng, kém chắc hơn should ở đây.",
        d: "shouldn't trái với ý khuyên đi khám.",
      },
    }),
    mcq({
      id: "mccs-11",
      difficulty: "hard",
      stem: "Excuse me, ___ I use your charger for five minutes?",
      choices: {
        a: "Should",
        b: "Could",
        c: "Must",
        d: "Would rather",
      },
      answer: "b",
      explanation: "Xin phép lịch sự dùng Could I ...?",
      whyWrong: {
        a: "Should I use hỏi có nên dùng không, không phải xin phép.",
        c: "Must I use mang nghĩa bắt buộc, không phải xin phép.",
        d: "Would rather nói sở thích, không xin phép mượn đồ.",
      },
    }),
    mcq({
      id: "mccs-12",
      difficulty: "hard",
      stem: "He ___ finish the project alone yesterday, so his teammates ___ help him today.",
      choices: {
        a: "couldn't / should",
        b: "can't / should",
        c: "shouldn't / could",
        d: "could / shouldn't",
      },
      answer: "a",
      explanation: "yesterday → couldn't finish; hôm nay cần lời khuyên/việc nên làm → should help.",
      whyWrong: {
        b: "can't không khớp yesterday.",
        c: "shouldn't finish trái với ý không làm nổi; could help yếu hơn should trong vai trò 'nên giúp'.",
        d: "could finish khẳng định làm được một mình, trái ngữ cảnh nhờ giúp.",
      },
    }),
  ],
};
