import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const passiveVoice: TopicSeed = {
  id: "topic-passive",
  slug: "passive-voice",
  name: "Passive Voice",
  gradeFrom: 9,
  gradeTo: 12,
  summary: "Nhấn vào người hoặc vật chịu tác động, không nhấn người làm.",
  purpose: "Khi người làm không quan trọng, không biết, hoặc người chịu tác động mới là trọng tâm.",
  usage: [
    "be + V3: be chia đúng thì, cộng quá khứ phân từ.",
    "by + người làm: thêm khi cần nói ai làm.",
  ].join("\n"),
  structure: [
    "Mẫu: chủ ngữ chịu tác động + be + V3 (+ by người làm).",
    "Thì: nằm ở be, không nằm ở động từ chính.",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + be + V3.",
  negativePattern: "Chủ ngữ + be + not + V3.",
  questionPattern: "Be + chủ ngữ + V3?",
  signalWords: ["by", "is made", "was built", "will be done"],
  examples: [
    { sentence: "This cake was made by my aunt yesterday.", note: "was mang quá khứ, made là phân từ." },
    { sentence: "English is spoken in many countries.", note: "Không cần nêu ai nói." },
    { sentence: "A new library will be built next year.", note: "will be built là tương lai bị động." },
  ],
  commonMistakes: [
    { wrong: "The cake made by my aunt.", right: "The cake was made by my aunt.", why: "Bị động cần be." },
    { wrong: "The letters sent yesterday.", right: "The letters were sent yesterday.", why: "letters số nhiều, quá khứ của be là were." },
    { wrong: "A library will build next year.", right: "A library will be built next year.", why: "Thư viện không tự xây. Cần be và phân từ built." },
  ],
  comparisons: [
    { with: "Active voice", note: "My aunt made this cake nhấn người làm. This cake was made by my aunt nhấn cái bánh." },
  ],
  prerequisiteSlugs: ["present-simple", "past-simple"],
  questions: [
    mcq({
      id: "pv-1",
      difficulty: "easy",
      stem: "This cake ___ by my aunt yesterday.",
      choices: { a: "made", b: "was made", c: "makes", d: "is making" },
      answer: "b",
      explanation: "Cái bánh chịu tác động, yesterday đưa be về was, phân từ là made.",
      whyWrong: {
        a: "made thiếu be, thành câu thiếu chủ ngữ người làm.",
        c: "makes là chủ động hiện tại.",
        d: "is making là chủ động tiếp diễn.",
      },
    }),
    mcq({
      id: "pv-2",
      difficulty: "easy",
      stem: "English ___ in many countries.",
      choices: { a: "speaks", b: "is spoken", c: "spoke", d: "is speaking" },
      answer: "b",
      explanation: "English là vật được nói, hiện tại đơn bị động là is spoken.",
      whyWrong: {
        a: "speaks biến English thành người nói.",
        c: "spoke là quá khứ chủ động.",
        d: "is speaking là chủ động tiếp diễn.",
      },
    }),
    mcq({
      id: "pv-3",
      difficulty: "medium",
      stem: "The invitation letters ___ yesterday afternoon.",
      choices: { a: "sent", b: "were sent", c: "are sent", d: "have sent" },
      answer: "b",
      explanation: "letters số nhiều và yesterday afternoon nên were sent.",
      whyWrong: {
        a: "sent thiếu were.",
        c: "are sent là hiện tại, lệch với yesterday afternoon.",
        d: "have sent là chủ động và thiếu been nếu muốn bị động.",
      },
    }),
    mcq({
      id: "pv-4",
      difficulty: "medium",
      stem: "The classroom ___ every morning before students arrive.",
      choices: { a: "cleans", b: "is cleaned", c: "cleaned", d: "is cleaning" },
      answer: "b",
      explanation: "Phòng được dọn theo thói quen, hiện tại đơn bị động: is cleaned.",
      whyWrong: {
        a: "cleans là chủ động, phòng không tự dọn.",
        c: "cleaned thiếu be và nghe như quá khứ.",
        d: "is cleaning là chủ động tiếp diễn.",
      },
    }),
    mcq({
      id: "pv-5",
      difficulty: "hard",
      stem: "The window ___ by the storm last night.",
      choices: { a: "broke", b: "was broken", c: "is broken", d: "breaks" },
      answer: "b",
      explanation: "by the storm và last night kể sự việc đã xảy ra: was broken.",
      whyWrong: {
        a: "broke là chủ động. Cửa sổ không phải người làm nếu có by the storm theo kiểu này.",
        c: "is broken tả trạng thái hiện tại, last night cần quá khứ.",
        d: "breaks là hiện tại đơn chủ động.",
      },
    }),
    mcq({
      id: "pv-6",
      difficulty: "hard",
      stem: "A new library ___ in our town next year.",
      choices: { a: "builds", b: "will be built", c: "will build", d: "is building" },
      answer: "b",
      explanation: "Thư viện là vật được xây trong tương lai: will be built.",
      whyWrong: {
        a: "builds là hiện tại chủ động.",
        c: "will build thiếu be và phân từ, nghe như thư viện tự xây.",
        d: "is building là việc đang xảy ra lúc nói.",
      },
    }),
    mcq({
      id: "pv-7",
      difficulty: "easy",
      stem: "These shoes ___ in Vietnam.",
      choices: { a: "make", b: "are made", c: "made", d: "are making" },
      answer: "b",
      explanation: "shoes số nhiều và chịu tác động ở hiện tại: are made.",
      whyWrong: {
        a: "make là chủ động, giày không tự làm.",
        c: "made thiếu be.",
        d: "are making là chủ động tiếp diễn.",
      },
    }),
    mcq({
      id: "pv-8",
      difficulty: "easy",
      stem: "The school gate ___ every evening at 9 p.m.",
      choices: { a: "locks", b: "is locked", c: "locked", d: "is locking" },
      answer: "b",
      explanation: "Cổng được khóa theo thói quen, hiện tại đơn bị động: is locked.",
      whyWrong: {
        a: "locks là chủ động, cổng không tự khóa.",
        c: "locked thiếu be.",
        d: "is locking là chủ động tiếp diễn.",
      },
    }),
    mcq({
      id: "pv-9",
      difficulty: "medium",
      stem: "The packages ___ to the wrong address last Monday.",
      choices: { a: "delivered", b: "were delivered", c: "are delivered", d: "have delivered" },
      answer: "b",
      explanation: "packages số nhiều và last Monday nên were delivered.",
      whyWrong: {
        a: "delivered thiếu were.",
        c: "are delivered là hiện tại, lệch với last Monday.",
        d: "have delivered là chủ động và thiếu been nếu muốn bị động.",
      },
    }),
    mcq({
      id: "pv-10",
      difficulty: "medium",
      stem: "The test results ___ to students tomorrow morning.",
      choices: { a: "announce", b: "will be announced", c: "will announce", d: "are announcing" },
      answer: "b",
      explanation: "Kết quả chịu tác động trong tương lai: will be announced.",
      whyWrong: {
        a: "announce là chủ động hiện tại.",
        c: "will announce thiếu be và phân từ.",
        d: "are announcing là chủ động tiếp diễn.",
      },
    }),
    mcq({
      id: "pv-11",
      difficulty: "hard",
      stem: "This essay ___ before Friday.",
      choices: { a: "must finish", b: "must be finished", c: "must finished", d: "must be finish" },
      answer: "b",
      explanation: "Bị động với must: must + be + V3 → must be finished.",
      whyWrong: {
        a: "must finish là chủ động, bài luận không tự hoàn thành.",
        c: "must finished thiếu be.",
        d: "must be finish sai vì sau be cần phân từ finished.",
      },
    }),
    mcq({
      id: "pv-12",
      difficulty: "hard",
      stem: "The stolen bike ___ yet.",
      choices: { a: "isn't found", b: "hasn't been found", c: "wasn't find", d: "hasn't found" },
      answer: "b",
      explanation: "yet báo hiện tại hoàn thành bị động: hasn't been found.",
      whyWrong: {
        a: "isn't found là hiện tại đơn/trạng thái, không hợp với yet theo kiểu hoàn thành.",
        c: "wasn't find sai thì và sai dạng find; cần found.",
        d: "hasn't found là chủ động và thiếu been.",
      },
    }),
  ],
};
