import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const pastPerfect: TopicSeed = {
  id: "topic-past-perfect",
  slug: "past-perfect",
  name: "Past Perfect",
  gradeFrom: 9,
  gradeTo: 12,
  summary: "Việc đã xảy ra trước một mốc hoặc sự kiện khác trong quá khứ.",
  purpose: "Làm rõ thứ tự: việc nào hoàn tất trước việc quá khứ đơn.",
  usage: [
    "had + V3: hành động xảy ra sớm hơn.",
    "Quá khứ đơn: hành động xảy ra sau.",
    "before, after, by the time, already, when: hay đi kèm khi có hai mốc quá khứ rõ.",
  ].join("\n"),
  structure: [
    "Khẳng định: chủ ngữ + had + quá khứ phân từ (V3).",
    "Phủ định: had not + V3.",
    "Câu hỏi: Had + chủ ngữ + V3?",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + had + V3 (+ before/when + quá khứ đơn).",
  negativePattern: "Chủ ngữ + had not + V3.",
  questionPattern: "Had + chủ ngữ + V3 before + quá khứ đơn?",
  signalWords: ["before", "after", "by the time", "already", "when", "until"],
  examples: [
    {
      sentence: "She had finished her homework before her mother came home.",
      note: "finished xảy ra trước came.",
    },
    {
      sentence: "By the time we arrived, the film had already started.",
      note: "by the time + quá khứ đơn; việc chiếu phim dùng past perfect.",
    },
    {
      sentence: "He was tired because he had run five kilometers.",
      note: "had run giải thích trạng thái was tired.",
    },
  ],
  commonMistakes: [
    {
      wrong: "She finished her homework before her mother had come home.",
      right: "She had finished her homework before her mother came home.",
      why: "Việc sớm hơn (làm bài) dùng had + V3; việc sau (mẹ về) dùng quá khứ đơn.",
    },
    {
      wrong: "By the time we arrived, the film already started.",
      right: "By the time we arrived, the film had already started.",
      why: "By the time + quá khứ đơn cần past perfect ở vế việc đã xảy trước.",
    },
    {
      wrong: "He had went out when I called.",
      right: "He had gone out when I called.",
      why: "Sau had phải dùng phân từ gone, không dùng went.",
    },
  ],
  comparisons: [
    {
      with: "Past simple",
      note: "Một mốc quá khứ dùng quá khứ đơn: I ate at 7. Hai mốc và cần nhấn việc trước dùng past perfect: I had eaten before he arrived.",
    },
    {
      with: "Present perfect",
      note: "Present perfect nối với hiện tại: I have lost my keys (vẫn mất). Past perfect nằm hoàn toàn trong quá khứ: I had lost my keys, so I called a locksmith.",
    },
  ],
  prerequisiteSlugs: ["past-simple", "present-perfect"],
  questions: [
    mcq({
      id: "ppf-1",
      difficulty: "easy",
      stem: "She ___ her homework before dinner.",
      choices: {
        a: "finishes",
        b: "had finished",
        c: "has finished",
        d: "is finishing",
      },
      answer: "b",
      explanation: "before dinner đặt việc làm bài sớm hơn trong quá khứ, dùng had finished.",
      whyWrong: {
        a: "finishes là hiện tại đơn.",
        c: "has finished nối với hiện tại, không khớp khung quá khứ của before dinner trong bài này.",
        d: "is finishing là hiện tại tiếp diễn.",
      },
    }),
    mcq({
      id: "ppf-2",
      difficulty: "easy",
      stem: "By the time the teacher entered, the students ___ the test papers.",
      choices: {
        a: "collect",
        b: "had collected",
        c: "have collected",
        d: "are collecting",
      },
      answer: "b",
      explanation: "By the time + entered (quá khứ), việc thu giấy xảy trước: had collected.",
      whyWrong: {
        a: "collect là hiện tại.",
        c: "have collected là hiện tại hoàn thành.",
        d: "are collecting là hiện tại tiếp diễn.",
      },
    }),
    mcq({
      id: "ppf-3",
      difficulty: "easy",
      stem: "He was hungry because he ___ breakfast.",
      choices: {
        a: "doesn't eat",
        b: "hadn't eaten",
        c: "hasn't eaten",
        d: "isn't eating",
      },
      answer: "b",
      explanation: "was hungry ở quá khứ; nguyên nhân trước đó dùng hadn't eaten.",
      whyWrong: {
        a: "doesn't eat là hiện tại đơn.",
        c: "hasn't eaten nối với hiện tại, trong khi was là quá khứ.",
        d: "isn't eating là hiện tại tiếp diễn phủ định.",
      },
    }),
    mcq({
      id: "ppf-4",
      difficulty: "easy",
      stem: "After they ___ the room, they left the building.",
      choices: {
        a: "clean",
        b: "had cleaned",
        c: "have cleaned",
        d: "are cleaning",
      },
      answer: "b",
      explanation: "After + việc sớm hơn: had cleaned, rồi left.",
      whyWrong: {
        a: "clean chưa chia đúng thì quá khứ hoàn thành.",
        c: "have cleaned là hiện tại hoàn thành.",
        d: "are cleaning là hiện tại tiếp diễn.",
      },
    }),
    mcq({
      id: "ppf-5",
      difficulty: "medium",
      stem: "When I arrived at the station, the train ___.",
      choices: {
        a: "already left",
        b: "had already left",
        c: "has already left",
        d: "is already leaving",
      },
      answer: "b",
      explanation: "arrived là mốc sau; tàu đi trước đó: had already left.",
      whyWrong: {
        a: "already left thiếu had.",
        c: "has already left là hiện tại hoàn thành.",
        d: "is already leaving là hiện tại tiếp diễn.",
      },
    }),
    mcq({
      id: "ppf-6",
      difficulty: "medium",
      stem: "They ___ each other for years before they got married.",
      choices: {
        a: "know",
        b: "had known",
        c: "have known",
        d: "are knowing",
      },
      answer: "b",
      explanation: "before they got married đặt khoảng thời gian quen nhau vào trước mốc quá khứ: had known.",
      whyWrong: {
        a: "know là hiện tại.",
        c: "have known nối tới hiện tại; câu đã có got married ở quá khứ.",
        d: "are knowing không dùng cho know theo nghĩa quen biết.",
      },
    }),
    mcq({
      id: "ppf-7",
      difficulty: "medium",
      stem: "I couldn't get in because I ___ my key at school.",
      choices: {
        a: "leave",
        b: "had left",
        c: "have left",
        d: "am leaving",
      },
      answer: "b",
      explanation: "couldn't get in ở quá khứ; quên chìa xảy trước: had left.",
      whyWrong: {
        a: "leave là nguyên mẫu.",
        c: "have left là hiện tại hoàn thành.",
        d: "am leaving là hiện tại tiếp diễn.",
      },
    }),
    mcq({
      id: "ppf-8",
      difficulty: "medium",
      stem: "___ you ___ the email before the meeting started?",
      choices: {
        a: "Have / sent",
        b: "Had / sent",
        c: "Did / sent",
        d: "Do / send",
      },
      answer: "b",
      explanation: "before the meeting started cần Had you sent.",
      whyWrong: {
        a: "Have you sent là hiện tại hoàn thành.",
        c: "Did you sent sai vì sau did dùng nguyên mẫu send, và cũng không tạo past perfect.",
        d: "Do you send là hiện tại đơn.",
      },
    }),
    mcq({
      id: "ppf-9",
      difficulty: "hard",
      stem: "The streets were wet. It ___ heavily earlier that morning.",
      choices: {
        a: "rains",
        b: "had rained",
        c: "has rained",
        d: "is raining",
      },
      answer: "b",
      explanation: "were wet ở quá khứ; mưa sớm hơn giải thích kết quả: had rained.",
      whyWrong: {
        a: "rains là hiện tại đơn.",
        c: "has rained nối với hiện tại.",
        d: "is raining là hiện tại tiếp diễn.",
      },
    }),
    mcq({
      id: "ppf-10",
      difficulty: "hard",
      stem: "She didn't watch the film because she ___ it three times before.",
      choices: {
        a: "sees",
        b: "had seen",
        c: "has seen",
        d: "was seeing",
      },
      answer: "b",
      explanation: "didn't watch ở quá khứ; việc xem trước đó dùng had seen.",
      whyWrong: {
        a: "sees là hiện tại đơn.",
        c: "has seen là hiện tại hoàn thành; khung câu là quá khứ với didn't watch.",
        d: "was seeing không diễn đạt kinh nghiệm đã xem xong trước đó.",
      },
    }),
    mcq({
      id: "ppf-11",
      difficulty: "hard",
      stem: "Until he ___ the instructions, he made several mistakes.",
      choices: {
        a: "reads",
        b: "had read",
        c: "has read",
        d: "is reading",
      },
      answer: "b",
      explanation: "Until + việc đọc xong trước khi made mistakes: had read.",
      whyWrong: {
        a: "reads là hiện tại đơn.",
        c: "has read là hiện tại hoàn thành.",
        d: "is reading là hiện tại tiếp diễn.",
      },
    }),
    mcq({
      id: "ppf-12",
      difficulty: "hard",
      stem: "We went to the museum that we ___ about in class the week before.",
      choices: {
        a: "learn",
        b: "had learned",
        c: "have learned",
        d: "are learning",
      },
      answer: "b",
      explanation: "went là mốc sau; học trên lớp tuần trước đó dùng had learned.",
      whyWrong: {
        a: "learn là hiện tại.",
        c: "have learned nối với hiện tại, không khớp went ở quá khứ.",
        d: "are learning là hiện tại tiếp diễn.",
      },
    }),
  ],
};
