import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const pastContinuous: TopicSeed = {
  id: "topic-past-continuous",
  slug: "past-continuous",
  name: "Past Continuous",
  gradeFrom: 7,
  gradeTo: 12,
  summary: "Việc đang diễn ra tại một thời điểm trong quá khứ, hoặc làm nền cho sự kiện khác.",
  purpose:
    "Mô tả hành động đang tiếp diễn ở một mốc quá khứ, hai việc song song, hoặc nền cảnh bị việc khác cắt ngang.",
  usage: [
    "at 8 p.m. yesterday: việc đang diễn ra tại một mốc trong quá khứ.",
    "while, when + quá khứ đơn: đang làm A thì B xảy ra, hay gặp khi kể chuyện.",
    "Không dùng: cho việc ngắn đã xong hoàn toàn, trừ khi cần nhấn mạnh quá trình.",
  ].join("\n"),
  structure: [
    "Khẳng định: was / were + V-ing.",
    "was: đi với I, he, she, it.",
    "were: đi với you, we, they.",
    "Phủ định: thêm not.",
    "Câu hỏi: đảo was / were lên trước chủ ngữ.",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + was/were + V-ing.",
  negativePattern: "Chủ ngữ + was/were + not + V-ing.",
  questionPattern: "Was/Were + chủ ngữ + V-ing?",
  signalWords: [
    "at 7 p.m. yesterday",
    "while",
    "when",
    "all evening",
    "at that time",
    "as",
  ],
  examples: [
    {
      sentence: "At 8 p.m. last night, I was doing homework.",
      note: "Mốc giờ trong quá khứ + was/were + V-ing.",
    },
    {
      sentence: "She was cooking when the phone rang.",
      note: "Nền tiếp diễn (was cooking) bị việc ngắn cắt ngang (rang).",
    },
    {
      sentence: "While we were waiting, it started to rain.",
      note: "while + quá khứ tiếp diễn cho việc kéo dài.",
    },
    {
      sentence: "They weren't watching TV at that time.",
      note: "Phủ định: weren't + V-ing.",
    },
  ],
  commonMistakes: [
    {
      wrong: "I were studying at 9.",
      right: "I was studying at 9.",
      why: "I đi với was, không đi với were.",
    },
    {
      wrong: "She was cook dinner when I arrived.",
      right: "She was cooking dinner when I arrived.",
      why: "Sau was/were phải là V-ing.",
    },
    {
      wrong: "While I watched TV, the lights went out.",
      right: "While I was watching TV, the lights went out.",
      why: "while thường đi với quá khứ tiếp diễn để nhấn mạnh việc đang diễn ra.",
    },
  ],
  comparisons: [
    {
      with: "Past simple",
      note: "Quá khứ tiếp diễn là nền đang diễn ra: I was walking home. Quá khứ đơn là việc cắt ngang hoặc sự kiện đã xong: when it started to rain.",
    },
    {
      with: "Present continuous",
      note: "Hiện tại tiếp diễn dùng am/is/are + V-ing cho lúc nói. Quá khứ tiếp diễn dùng was/were + V-ing cho mốc đã qua.",
    },
  ],
  prerequisiteSlugs: ["past-simple", "present-continuous"],
  questions: [
    mcq({
      id: "pco-1",
      difficulty: "easy",
      stem: "At 9 p.m. yesterday, she ___ a novel.",
      choices: {
        a: "reads",
        b: "was reading",
        c: "is reading",
        d: "readed",
      },
      answer: "b",
      explanation: "Mốc giờ trong quá khứ cần was reading.",
      whyWrong: {
        a: "reads là hiện tại đơn.",
        c: "is reading là hiện tại tiếp diễn.",
        d: "readed không phải dạng đúng; quá khứ của read là read.",
      },
    }),
    mcq({
      id: "pco-2",
      difficulty: "easy",
      stem: "They ___ football when it started to rain.",
      choices: {
        a: "played",
        b: "were playing",
        c: "are playing",
        d: "play",
      },
      answer: "b",
      explanation: "Việc đang diễn ra (were playing) bị mưa cắt ngang (started).",
      whyWrong: {
        a: "played biến cả hai thành sự kiện ngắn liên tiếp, kém rõ nền đang đá.",
        c: "are playing là hiện tại.",
        d: "play là hiện tại đơn.",
      },
    }),
    mcq({
      id: "pco-3",
      difficulty: "easy",
      stem: "___ you sleeping when I called?",
      choices: {
        a: "Was",
        b: "Were",
        c: "Are",
        d: "Did",
      },
      answer: "b",
      explanation: "you đi với Were trong quá khứ tiếp diễn: Were you sleeping...?",
      whyWrong: {
        a: "Was không đi với you.",
        c: "Are là hiện tại.",
        d: "Did tạo quá khứ đơn, không đi với sleeping theo cấu trúc này.",
      },
    }),
    mcq({
      id: "pco-4",
      difficulty: "easy",
      stem: "I ___ TV at that time; I was studying.",
      choices: {
        a: "wasn't watching",
        b: "didn't watching",
        c: "am not watching",
        d: "don't watch",
      },
      answer: "a",
      explanation: "Phủ định quá khứ tiếp diễn: wasn't watching.",
      whyWrong: {
        b: "didn't không đi với watching; sau didn't phải là nguyên mẫu.",
        c: "am not watching là hiện tại.",
        d: "don't watch là hiện tại đơn.",
      },
    }),
    mcq({
      id: "pco-5",
      difficulty: "medium",
      stem: "While he ___ the dishes, the doorbell rang.",
      choices: {
        a: "washed",
        b: "was washing",
        c: "is washing",
        d: "washes",
      },
      answer: "b",
      explanation: "while + quá khứ tiếp diễn cho nền đang rửa, rung chuông cắt ngang.",
      whyWrong: {
        a: "washed làm mất cảm giác việc đang diễn ra khi chuông reo.",
        c: "is washing là hiện tại.",
        d: "washes là hiện tại đơn.",
      },
    }),
    mcq({
      id: "pco-6",
      difficulty: "medium",
      stem: "We ___ for the bus when we saw our teacher.",
      choices: {
        a: "waited",
        b: "were waiting",
        c: "wait",
        d: "have waited",
      },
      answer: "b",
      explanation: "Đang chờ thì thấy giáo viên: were waiting + saw.",
      whyWrong: {
        a: "waited có thể hiểu là đã chờ xong, kém khớp nền bị cắt ngang.",
        c: "wait là hiện tại.",
        d: "have waited là hiện tại hoàn thành.",
      },
    }),
    mcq({
      id: "pco-7",
      difficulty: "medium",
      stem: "What ___ she ___ at 7 o'clock last night?",
      choices: {
        a: "did / do",
        b: "was / doing",
        c: "is / doing",
        d: "has / done",
      },
      answer: "b",
      explanation: "Hỏi việc đang diễn ra tại một giờ quá khứ: was she doing.",
      whyWrong: {
        a: "did/do hỏi sự kiện quá khứ đơn, không nhấn mạnh quá trình tại 7 giờ.",
        c: "is/doing là hiện tại.",
        d: "has/done là hiện tại hoàn thành.",
      },
    }),
    mcq({
      id: "pco-8",
      difficulty: "medium",
      stem: "As the teacher explained the rule, the students ___ quietly.",
      choices: {
        a: "take notes",
        b: "were taking notes",
        c: "are taking notes",
        d: "have taken notes",
      },
      answer: "b",
      explanation: "as + nền quá khứ: học sinh đang ghi chép song song lúc giáo viên giải thích → were taking notes.",
      whyWrong: {
        a: "take notes là hiện tại đơn.",
        c: "are taking notes là hiện tại tiếp diễn.",
        d: "have taken notes là hiện tại hoàn thành, không kể nền lúc đó.",
      },
    }),
    mcq({
      id: "pco-9",
      difficulty: "hard",
      stem: "I ___ along the river when a bicycle nearly hit me.",
      choices: {
        a: "walked",
        b: "was walking",
        c: "have walked",
        d: "am walking",
      },
      answer: "b",
      explanation: "Nền đang đi bộ bị sự cố cắt ngang: was walking ... when ... hit.",
      whyWrong: {
        a: "walked kém rõ việc đang diễn ra ngay trước khi gần bị đụng.",
        c: "have walked nối tới hiện tại, không kể sự cố quá khứ này.",
        d: "am walking là hiện tại.",
      },
    }),
    mcq({
      id: "pco-10",
      difficulty: "hard",
      stem: "While Mum ___, Dad ___ the living room.",
      choices: {
        a: "cooked / cleaned",
        b: "was cooking / was cleaning",
        c: "cooks / cleans",
        d: "is cooking / cleaned",
      },
      answer: "b",
      explanation: "Hai hành động kéo dài song song trong quá khứ dùng was/were + V-ing cho cả hai.",
      whyWrong: {
        a: "cooked/cleaned biến thành chuỗi sự kiện đã xong, không nhấn mạnh song song.",
        c: "cooks/cleans là hiện tại đơn.",
        d: "Trộn hiện tại và quá khứ, không thống nhất.",
      },
    }),
    mcq({
      id: "pco-11",
      difficulty: "hard",
      stem: "He broke the glass while he ___ the table.",
      choices: {
        a: "set",
        b: "was setting",
        c: "sets",
        d: "has set",
      },
      answer: "b",
      explanation: "broke là sự kiện ngắn trong lúc đang bày bàn: was setting.",
      whyWrong: {
        a: "set ở quá khứ đơn làm mất nền đang diễn ra.",
        c: "sets là hiện tại.",
        d: "has set là hiện tại hoàn thành.",
      },
    }),
    mcq({
      id: "pco-12",
      difficulty: "hard",
      stem: "Sorry I missed your call. I ___ in a meeting at that time yesterday.",
      choices: {
        a: "sit",
        b: "was sitting",
        c: "am sitting",
        d: "have sat",
      },
      answer: "b",
      explanation: "at that time yesterday khóa một mốc quá khứ đang diễn ra: was sitting.",
      whyWrong: {
        a: "sit là hiện tại.",
        c: "am sitting là hiện tại tiếp diễn.",
        d: "have sat không đi với yesterday theo cách này.",
      },
    }),
  ],
};
