import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const pastSimpleVsPresentPerfect: TopicSeed = {
  id: "topic-past-vs-perfect",
  slug: "past-simple-vs-present-perfect",
  name: "Past Simple và Present Perfect",
  gradeFrom: 9,
  gradeTo: 12,
  summary: "Chọn quá khứ đơn khi có mốc đã khép, hiện tại hoàn thành khi còn liên quan tới bây giờ.",
  purpose: "Phân biệt hai thì hay bị dùng lẫn khi trong câu có yesterday, since, just, hoặc một kết quả còn thấy.",
  usage: [
    "Mẹo: nhìn từ chỉ thời gian trước.",
    "yesterday: mốc đã khép, dùng quá khứ đơn.",
    "since, for, just, already, yet, ever, never: thường dùng hiện tại hoàn thành.",
  ].join("\n"),
  structure: [
    "Quá khứ đơn: một động từ ở cột 2 (V2).",
    "Hiện tại hoàn thành: have / has + cột 3 (V3).",
  ].join("\n"),
  affirmativePattern: "Quá khứ: V2. Hoàn thành: have/has + V3.",
  negativePattern: "Quá khứ: did not + V. Hoàn thành: have/has not + V3.",
  questionPattern: "Quá khứ: Did + chủ ngữ + V? Hoàn thành: Have/Has + chủ ngữ + V3?",
  signalWords: ["yesterday", "last summer", "since", "for", "just", "already", "yet", "ever", "never"],
  examples: [
    { sentence: "I saw a strange bird yesterday.", note: "Có yesterday nên quá khứ đơn." },
    { sentence: "She has lost her keys, so she cannot open the door.", note: "Kết quả còn đúng lúc nói." },
    { sentence: "They have lived here since March 2020.", note: "since giữ hiện tại hoàn thành." },
  ],
  commonMistakes: [
    { wrong: "I have seen him yesterday.", right: "I saw him yesterday.", why: "Mốc đã khép không đi với have." },
    { wrong: "We have visited that museum last summer.", right: "We visited that museum last summer.", why: "last summer đã kết thúc." },
    { wrong: "They lived here since 2020.", right: "They have lived here since 2020.", why: "since kèm việc còn tiếp diễn cần have." },
  ],
  comparisons: [
    { with: "Chính hai thì này", note: "Cùng một động từ đổi nghĩa khi đổi thì. I lost my keys kể một lần trong quá khứ. I have lost my keys nói hậu quả còn đó." },
  ],
  prerequisiteSlugs: ["past-simple", "present-perfect"],
  questions: [
    mcq({
      id: "cmp-1",
      difficulty: "easy",
      stem: "I ___ a strange bird in the garden yesterday.",
      choices: { a: "have seen", b: "saw", c: "see", d: "am seeing" },
      answer: "b",
      explanation: "yesterday khép thời gian, nên saw.",
      whyWrong: {
        a: "have seen không đi cùng yesterday.",
        c: "see là hiện tại.",
        d: "am seeing là việc đang xảy ra lúc nói.",
      },
    }),
    mcq({
      id: "cmp-2",
      difficulty: "easy",
      stem: "She ___ her keys, so she cannot open the door now.",
      choices: { a: "lost", b: "has lost", c: "loses", d: "was losing" },
      answer: "b",
      explanation: "Không có mốc quá khứ, và kết quả còn đúng lúc này, nên has lost.",
      whyWrong: {
        a: "lost cần một thời điểm quá khứ hoặc chỉ kể chuyện đã xong, câu này nhấn hậu quả hiện tại.",
        c: "loses là thói quen.",
        d: "was losing là quá khứ tiếp diễn, không phải kết quả còn lại.",
      },
    }),
    mcq({
      id: "cmp-3",
      difficulty: "medium",
      stem: "They ___ in this city since March 2020.",
      choices: { a: "lived", b: "have lived", c: "live", d: "had lived" },
      answer: "b",
      explanation: "since March 2020 và việc còn tiếp diễn dùng have lived.",
      whyWrong: {
        a: "lived không đi với since khi khoảng thời gian còn tới hiện tại.",
        c: "live bỏ qua since. Câu có since cần hoàn thành.",
        d: "had lived là quá khứ của một quá khứ khác, câu không có mốc thứ hai.",
      },
    }),
    mcq({
      id: "cmp-4",
      difficulty: "medium",
      stem: "We ___ that museum last summer.",
      choices: { a: "have visited", b: "visited", c: "visit", d: "are visiting" },
      answer: "b",
      explanation: "last summer đã qua, nên visited.",
      whyWrong: {
        a: "have visited không gắn với last summer.",
        c: "visit là thói quen hoặc hiện tại.",
        d: "are visiting là hiện tại, không phải mùa hè năm ngoái.",
      },
    }),
    mcq({
      id: "cmp-5",
      difficulty: "hard",
      stem: "Minh has ___ tried pho, so he does not know the taste.",
      choices: { a: "ever", b: "never", c: "already", d: "yet" },
      answer: "b",
      explanation: "Anh ấy chưa biết vị, nên kinh nghiệm ở dạng phủ định: has never tried.",
      whyWrong: {
        a: "ever dùng trong câu hỏi, không tạo nghĩa chưa từng ở câu này.",
        c: "already nghĩa là đã làm rồi, trái với việc chưa biết vị.",
        d: "yet không đứng giữa has và tried theo kiểu này.",
      },
    }),
    mcq({
      id: "cmp-6",
      difficulty: "hard",
      stem: "___ you meet the new teacher at school yesterday?",
      choices: { a: "Have", b: "Did", c: "Do", d: "Are" },
      answer: "b",
      explanation: "yesterday buộc câu hỏi quá khứ đơn: Did you meet.",
      whyWrong: {
        a: "Have you meet vừa sai thì vừa thiếu phân từ, và lệch với yesterday.",
        c: "Do là hiện tại.",
        d: "Are không hỏi meet theo cấu trúc này.",
      },
    }),
    mcq({
      id: "cmp-7",
      difficulty: "easy",
      stem: "I ___ that café two days ago.",
      choices: { a: "have visited", b: "visited", c: "visit", d: "am visiting" },
      answer: "b",
      explanation: "two days ago là mốc đã khép, nên visited.",
      whyWrong: {
        a: "have visited không đi với ago.",
        c: "visit là hiện tại.",
        d: "am visiting là việc đang xảy ra lúc nói.",
      },
    }),
    mcq({
      id: "cmp-8",
      difficulty: "easy",
      stem: "I ___ just spoken to the coach.",
      choices: { a: "have", b: "did", c: "do", d: "was" },
      answer: "a",
      explanation: "just với phân từ spoken dùng hiện tại hoàn thành: have just spoken.",
      whyWrong: {
        b: "did không đứng trước spoken; sau did phải là speak.",
        c: "do không tạo have + V3.",
        d: "was không đứng trước spoken theo mẫu này.",
      },
    }),
    mcq({
      id: "cmp-9",
      difficulty: "medium",
      stem: "Our school ___ a new computer lab in 2019.",
      choices: { a: "has built", b: "built", c: "builds", d: "is building" },
      answer: "b",
      explanation: "in 2019 là năm đã kết thúc, nên built.",
      whyWrong: {
        a: "has built không gắn với năm đã khép như 2019.",
        c: "builds là thói quen hiện tại.",
        d: "is building nói việc đang xây lúc này.",
      },
    }),
    mcq({
      id: "cmp-10",
      difficulty: "medium",
      stem: "___ you ever climbed Mount Fansipan?",
      choices: { a: "Did", b: "Have", c: "Do", d: "Are" },
      answer: "b",
      explanation: "ever hỏi kinh nghiệm, không có mốc đã khép: Have you ever climbed.",
      whyWrong: {
        a: "Did you ever climbed sai dạng; quá khứ đơn đúng là Did you ever climb, và câu này hỏi kinh nghiệm nên dùng Have.",
        c: "Do không đi với climbed.",
        d: "Are không hỏi climbed theo cấu trúc này.",
      },
    }),
    mcq({
      id: "cmp-11",
      difficulty: "hard",
      stem: "He ___ his phone an hour ago, so he cannot call us now.",
      choices: { a: "has lost", b: "lost", c: "loses", d: "is losing" },
      answer: "b",
      explanation: "an hour ago khóa thời gian đã khép, nên lost dù hậu quả còn thấy.",
      whyWrong: {
        a: "has lost hợp khi không có ago; có ago thì không dùng hiện tại hoàn thành.",
        c: "loses là thói quen.",
        d: "is losing là việc đang mất lúc nói.",
      },
    }),
    mcq({
      id: "cmp-12",
      difficulty: "hard",
      stem: "How many times ___ you been late this month?",
      choices: { a: "did", b: "have", c: "do", d: "were" },
      answer: "b",
      explanation: "this month chưa kết thúc và been là phân từ, nên have you been.",
      whyWrong: {
        a: "did không đi với been, và this month chưa khép nên không chọn quá khứ đơn.",
        c: "do không đi với been.",
        d: "were không tạo câu hỏi been late theo mẫu này.",
      },
    }),
  ],
};
