import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const prepositionsTimePlace: TopicSeed = {
  id: "topic-prepositions-time-place",
  slug: "prepositions-time-place",
  name: "Prepositions of Time and Place",
  gradeFrom: 6,
  gradeTo: 12,
  summary: "Giới từ thời gian và nơi chốn: in, on, at và vài cặp dễ lẫn.",
  purpose: "Gắn mốc thời gian hoặc vị trí vào câu cho đúng quan hệ không gian và thời gian.",
  usage: [
    "at (thời gian): giờ cụ thể.",
    "on (thời gian): ngày, thứ trong tuần.",
    "in (thời gian): tháng, năm, buổi dài.",
    "at (nơi chốn): một điểm cụ thể.",
    "on (nơi chốn): bề mặt.",
    "in (nơi chốn): không gian kín hoặc khu vực lớn.",
  ].join("\n"),
  structure: [
    "at: + giờ, + điểm hoặc địa chỉ nhỏ.",
    "on: + ngày, + bề mặt.",
    "in: + tháng, năm, thành phố, phòng.",
    "Lưu ý: tránh chồng giới từ không cần thiết.",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + động từ + in/on/at + thời gian hoặc nơi chốn.",
  negativePattern: "Chủ ngữ + do/does/did not + động từ + in/on/at + ...",
  questionPattern: "Where/When + trợ động từ + chủ ngữ + động từ + giới từ?",
  signalWords: ["in", "on", "at", "under", "between", "next to"],
  examples: [
    {
      sentence: "The exam starts at 7:30 in the morning.",
      note: "at gắn với giờ điểm; in the morning là buổi.",
    },
    {
      sentence: "We have English on Monday in room 12.",
      note: "on + ngày trong tuần; in + phòng.",
    },
    {
      sentence: "She is waiting at the bus stop.",
      note: "at chỉ một điểm gặp mặt cụ thể.",
    },
  ],
  commonMistakes: [
    {
      wrong: "I was born in 15th July.",
      right: "I was born on 15th July.",
      why: "Ngày cụ thể trong tháng dùng on, không dùng in.",
    },
    {
      wrong: "The book is in the table.",
      right: "The book is on the table.",
      why: "Trên bề mặt bàn dùng on; in là bên trong.",
    },
    {
      wrong: "See you in the weekend.",
      right: "See you at the weekend.",
      why: "at the weekend là cách phổ biến trong tiếng Anh British ở chương trình phổ thông.",
    },
  ],
  comparisons: [
    {
      with: "In / on / at (time)",
      note: "in tháng năm buổi; on ngày và thứ; at giờ và một số cụm cố định như at noon, at night.",
    },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "prep-1",
      difficulty: "easy",
      stem: "The meeting begins ___ 8 o'clock.",
      choices: { a: "in", b: "on", c: "at", d: "by" },
      answer: "c",
      explanation: "Giờ điểm dùng at.",
      whyWrong: {
        a: "in không đi với giờ cụ thể kiểu 8 o'clock.",
        b: "on dùng cho ngày, không cho giờ.",
        d: "by 8 o'clock nghĩa là trước hoặc chậm nhất 8 giờ, không phải lúc bắt đầu đúng 8.",
      },
    }),
    mcq({
      id: "prep-2",
      difficulty: "easy",
      stem: "We usually play badminton ___ Sundays.",
      choices: { a: "in", b: "on", c: "at", d: "to" },
      answer: "b",
      explanation: "Ngày trong tuần dùng on.",
      whyWrong: {
        a: "in không đi với Sundays theo nghĩa thói quen ngày.",
        c: "at không dùng trước Sundays.",
        d: "to không chỉ thời gian ở đây.",
      },
    }),
    mcq({
      id: "prep-3",
      difficulty: "easy",
      stem: "She was born ___ 2008.",
      choices: { a: "in", b: "on", c: "at", d: "from" },
      answer: "a",
      explanation: "Năm dùng in.",
      whyWrong: {
        b: "on dùng cho ngày cụ thể, không cho cả năm.",
        c: "at không đi với năm.",
        d: "from cần một mốc kết thúc, ví dụ from 2008 to 2012.",
      },
    }),
    mcq({
      id: "prep-4",
      difficulty: "easy",
      stem: "There are some apples ___ the fridge.",
      choices: { a: "on", b: "at", c: "in", d: "over" },
      answer: "c",
      explanation: "Bên trong tủ lạnh dùng in.",
      whyWrong: {
        a: "on the fridge là trên nóc tủ, không phải bên trong.",
        b: "at the fridge không diễn tả đồ nằm bên trong.",
        d: "over nói phía trên theo hướng khác, không phải trong tủ.",
      },
    }),
    mcq({
      id: "prep-5",
      difficulty: "medium",
      stem: "Please put the keys ___ the table near the door.",
      choices: { a: "in", b: "on", c: "at", d: "into" },
      answer: "b",
      explanation: "Đặt trên bề mặt bàn dùng on.",
      whyWrong: {
        a: "in the table sai vì bàn không phải không gian chứa để bỏ chìa vào.",
        c: "at the table thường nói người ngồi bàn, không nói vật nằm trên mặt bàn.",
        d: "into nhấn mạnh chuyển động vào trong, không phù hợp mặt bàn.",
      },
    }),
    mcq({
      id: "prep-6",
      difficulty: "medium",
      stem: "He often studies ___ night before a test.",
      choices: { a: "in", b: "on", c: "at", d: "by" },
      answer: "c",
      explanation: "Cụm cố định: at night.",
      whyWrong: {
        a: "in night không chuẩn; buổi dùng in the morning/afternoon/evening.",
        b: "on night sai.",
        d: "by night có nghĩa khác, ít dùng cho thói quen học bài.",
      },
    }),
    mcq({
      id: "prep-7",
      difficulty: "medium",
      stem: "They arrived ___ the airport two hours early.",
      choices: { a: "in", b: "on", c: "at", d: "to" },
      answer: "c",
      explanation: "arrive at + điểm cụ thể như airport, station.",
      whyWrong: {
        a: "arrive in dùng cho thành phố hoặc quốc gia lớn, không phải sân bay như điểm.",
        b: "arrive on the airport không đúng.",
        d: "arrive to là lỗi phổ biến; sau arrive không dùng to.",
      },
    }),
    mcq({
      id: "prep-8",
      difficulty: "medium",
      stem: "Independence Day in Vietnam is ___ 2nd September.",
      choices: { a: "in", b: "on", c: "at", d: "during" },
      answer: "b",
      explanation: "Ngày tháng cụ thể dùng on.",
      whyWrong: {
        a: "in September được, nhưng in 2nd September thì sai.",
        c: "at không đi với ngày tháng kiểu này.",
        d: "during cần một khoảng thời gian, không đi trực tiếp với 2nd September.",
      },
    }),
    mcq({
      id: "prep-9",
      difficulty: "hard",
      stem: "The post office is ___ the bank and the bookstore.",
      choices: { a: "among", b: "between", c: "across", d: "along" },
      answer: "b",
      explanation: "Giữa đúng hai địa điểm dùng between.",
      whyWrong: {
        a: "among dùng khi có từ ba trở lên hoặc trong đám đông.",
        c: "across là phía bên kia đường/sông, không phải kẹp giữa hai nơi.",
        d: "along là dọc theo, không chỉ vị trí kẹp giữa.",
      },
    }),
    mcq({
      id: "prep-10",
      difficulty: "hard",
      stem: "We stayed ___ Hue for three days ___ July.",
      choices: {
        a: "at / in",
        b: "in / in",
        c: "in / on",
        d: "on / in",
      },
      answer: "b",
      explanation: "Thành phố dùng in; tháng cũng dùng in: in Hue ... in July.",
      whyWrong: {
        a: "at Hue không hợp với thành phố; at dùng điểm nhỏ hơn.",
        c: "on July sai vì tháng dùng in.",
        d: "on Hue sai hoàn toàn cho thành phố.",
      },
    }),
    mcq({
      id: "prep-11",
      difficulty: "hard",
      stem: "Don't leave your bag ___ the floor; hang it ___ the hook.",
      choices: {
        a: "in / on",
        b: "on / on",
        c: "on / in",
        d: "at / in",
      },
      answer: "b",
      explanation: "on the floor là trên sàn; hang ... on the hook là treo trên móc.",
      whyWrong: {
        a: "in the floor sai vì sàn không phải không gian chứa chứa đồ vào.",
        c: "in the hook sai; móc không chứa túi theo nghĩa in.",
        d: "at the floor và in the hook đều không chỉ đúng vị trí.",
      },
    }),
    mcq({
      id: "prep-12",
      difficulty: "hard",
      stem: "She has lived here ___ 2019, so she knows the neighborhood well.",
      choices: { a: "in", b: "on", c: "at", d: "since" },
      answer: "d",
      explanation: "since + mốc bắt đầu với hiện tại hoàn thành: since 2019.",
      whyWrong: {
        a: "in 2019 khóa việc trong năm đó, không nói kéo dài tới nay.",
        b: "on không đi với năm.",
        c: "at không đi với năm.",
      },
    }),
  ],
};
