import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const presentContinuous: TopicSeed = {
  id: "topic-present-continuous",
  slug: "present-continuous",
  name: "Present Continuous",
  gradeFrom: 6,
  gradeTo: 12,
  summary: "Việc đang xảy ra lúc nói, xu hướng tạm thời, hoặc kế hoạch đã sắp xếp gần.",
  purpose:
    "Nói về hành động đang diễn ra ngay lúc nói, tình trạng tạm thời trong giai đoạn hiện tại, hoặc kế hoạch cá nhân đã cố định trong tương lai gần.",
  usage: [
    "now, at the moment, currently: việc đang diễn ra lúc nói.",
    "Mô tả tranh, video: việc đang diễn ra trong hình đang xem.",
    "Thay đổi dần: tình trạng đang tăng, giảm hoặc biến đổi.",
    "Lịch hẹn: kế hoạch cá nhân đã sắp xếp.",
    "Không dùng: với động từ trạng thái như know, like, belong khi chúng chỉ trạng thái ổn định.",
  ].join("\n"),
  structure: [
    "Khẳng định: am / is / are + V-ing.",
    "Phủ định: thêm not sau be.",
    "Câu hỏi: đảo am / is / are lên trước chủ ngữ.",
    "Tận cùng e: bỏ e rồi thêm -ing.",
    "Phụ âm - nguyên âm - phụ âm: động từ một âm tiết thường nhân đôi phụ âm cuối.",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + am/is/are + V-ing.",
  negativePattern: "Chủ ngữ + am/is/are + not + V-ing.",
  questionPattern: "Am/Is/Are + chủ ngữ + V-ing?",
  signalWords: [
    "now",
    "at the moment",
    "right now",
    "currently",
    "these days",
    "Look!",
    "Listen!",
  ],
  examples: [
    {
      sentence: "She is writing an email right now.",
      note: "right now khóa việc đang diễn ra lúc nói.",
    },
    {
      sentence: "I am staying with my aunt this week.",
      note: "this week là giai đoạn tạm, không phải thói quen lâu dài.",
    },
    {
      sentence: "We are meeting the coach tomorrow afternoon.",
      note: "Kế hoạch đã sắp xếp dùng hiện tại tiếp diễn.",
    },
    {
      sentence: "Look! The children are playing in the yard.",
      note: "Look! báo hiệu việc đang xảy ra trước mắt.",
    },
  ],
  commonMistakes: [
    {
      wrong: "She writing a letter now.",
      right: "She is writing a letter now.",
      why: "Thiếu be (is) trước V-ing.",
    },
    {
      wrong: "I am knowing the answer.",
      right: "I know the answer.",
      why: "know là động từ trạng thái, không dùng tiếp diễn khi chỉ hiểu biết.",
    },
    {
      wrong: "They is watching TV.",
      right: "They are watching TV.",
      why: "they đi với are, không đi với is.",
    },
    {
      wrong: "He doesn't working now.",
      right: "He isn't working now.",
      why: "Phủ định hiện tại tiếp diễn dùng isn't/aren't + V-ing, không dùng doesn't + working.",
    },
  ],
  comparisons: [
    {
      with: "Present simple",
      note: "Hiện tại đơn là thói quen hoặc sự thật: I study every night. Hiện tại tiếp diễn là việc đang xảy ra hoặc tạm thời: I am studying now.",
    },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "pc-1",
      difficulty: "easy",
      stem: "Quiet, please. The baby ___ right now.",
      choices: {
        a: "sleeps",
        b: "is sleeping",
        c: "sleep",
        d: "slept",
      },
      answer: "b",
      explanation: "right now chỉ việc đang xảy ra lúc nói, nên dùng is sleeping.",
      whyWrong: {
        a: "sleeps là hiện tại đơn cho thói quen, không khớp right now.",
        c: "sleep thiếu be và chưa chia cho the baby.",
        d: "slept là quá khứ, câu đang nói lúc này.",
      },
    }),
    mcq({
      id: "pc-2",
      difficulty: "easy",
      stem: "Look! They ___ football in the park.",
      choices: {
        a: "play",
        b: "plays",
        c: "are playing",
        d: "played",
      },
      answer: "c",
      explanation: "Look! báo hiệu việc đang diễn ra trước mắt, they đi với are playing.",
      whyWrong: {
        a: "play là hiện tại đơn, không nhấn mạnh việc đang thấy.",
        b: "plays chỉ ngôi thứ ba số ít, và cũng là hiện tại đơn.",
        d: "played đẩy việc về quá khứ.",
      },
    }),
    mcq({
      id: "pc-3",
      difficulty: "easy",
      stem: "I ___ with my cousin this month while my parents travel.",
      choices: {
        a: "stay",
        b: "stays",
        c: "am staying",
        d: "stayed",
      },
      answer: "c",
      explanation: "this month là tình trạng tạm thời, dùng am staying.",
      whyWrong: {
        a: "stay mang nghĩa thói quen ổn định hơn là tạm thời.",
        b: "stays không đi với I.",
        d: "stayed là quá khứ.",
      },
    }),
    mcq({
      id: "pc-4",
      difficulty: "easy",
      stem: "___ she doing her homework at the moment?",
      choices: {
        a: "Do",
        b: "Does",
        c: "Is",
        d: "Has",
      },
      answer: "c",
      explanation: "Câu hỏi hiện tại tiếp diễn đảo Is trước chủ ngữ: Is she doing...?",
      whyWrong: {
        a: "Do dùng cho câu hỏi hiện tại đơn với I/you/we/they.",
        b: "Does tạo câu hỏi hiện tại đơn, không đi với doing.",
        d: "Has không tạo hiện tại tiếp diễn với doing.",
      },
    }),
    mcq({
      id: "pc-5",
      difficulty: "medium",
      stem: "He ___ the guitar these days because he has a school concert.",
      choices: {
        a: "practices",
        b: "is practicing",
        c: "practiced",
        d: "practice",
      },
      answer: "b",
      explanation: "these days chỉ giai đoạn tạm đang diễn ra, dùng is practicing.",
      whyWrong: {
        a: "practices hợp thói quen lâu dài hơn; these days nhấn mạnh giai đoạn hiện tại.",
        c: "practiced là quá khứ.",
        d: "practice thiếu be và không khớp ngôi he.",
      },
    }),
    mcq({
      id: "pc-6",
      difficulty: "medium",
      stem: "We ___ dinner now. Can I call you back later?",
      choices: {
        a: "have",
        b: "are having",
        c: "had",
        d: "has",
      },
      answer: "b",
      explanation: "now và ngữ cảnh đang bận cho thấy việc đang diễn ra: are having.",
      whyWrong: {
        a: "have ở hiện tại đơn không nhấn mạnh việc đang ăn lúc nói.",
        c: "had là quá khứ.",
        d: "has không đi với we.",
      },
    }),
    mcq({
      id: "pc-7",
      difficulty: "medium",
      stem: "She isn't ___ to music; she is reading.",
      choices: {
        a: "listen",
        b: "listens",
        c: "listening",
        d: "listened",
      },
      answer: "c",
      explanation: "Sau isn't phải là V-ing: listening.",
      whyWrong: {
        a: "listen là nguyên mẫu, cần -ing sau isn't trong thì tiếp diễn.",
        b: "listens là hiện tại đơn đã chia.",
        d: "listened là quá khứ.",
      },
    }),
    mcq({
      id: "pc-8",
      difficulty: "medium",
      stem: "The number of online learners ___ every year.",
      choices: {
        a: "increase",
        b: "is increasing",
        c: "increased",
        d: "are increasing",
      },
      answer: "b",
      explanation: "Xu hướng đang thay đổi dần dùng hiện tại tiếp diễn; the number là số ít nên is increasing.",
      whyWrong: {
        a: "increase thiếu -s/be và không nhấn mạnh xu hướng đang diễn ra.",
        c: "increased chỉ việc đã tăng trong quá khứ.",
        d: "are không khớp với chủ ngữ số ít the number.",
      },
    }),
    mcq({
      id: "pc-9",
      difficulty: "hard",
      stem: "I ___ what you mean. Can you explain again?",
      choices: {
        a: "am not understanding",
        b: "don't understand",
        c: "am not understand",
        d: "not understand",
      },
      answer: "b",
      explanation: "understand là động từ trạng thái; phủ định dùng don't understand.",
      whyWrong: {
        a: "am not understanding ít dùng và không phải lựa chọn chuẩn trong bài tập dạng này.",
        c: "am not understand sai cấu trúc; sau am not cần V-ing nếu dùng tiếp diễn.",
        d: "not understand thiếu trợ động từ do/don't.",
      },
    }),
    mcq({
      id: "pc-10",
      difficulty: "hard",
      stem: "They ___ the museum at 3 p.m. tomorrow; the tickets are already booked.",
      choices: {
        a: "visited",
        b: "have visited",
        c: "are visiting",
        d: "were visiting",
      },
      answer: "c",
      explanation: "Kế hoạch cá nhân đã sắp xếp (vé đã đặt) dùng hiện tại tiếp diễn cho tương lai gần: are visiting.",
      whyWrong: {
        a: "visited là quá khứ.",
        b: "have visited nói trải nghiệm đã xảy ra, không phải lịch ngày mai.",
        d: "were visiting là quá khứ tiếp diễn.",
      },
    }),
    mcq({
      id: "pc-11",
      difficulty: "hard",
      stem: "You ___ always ___ your keys when we are already late!",
      choices: {
        a: "do / lose",
        b: "are / losing",
        c: "did / lose",
        d: "have / lost",
      },
      answer: "b",
      explanation: "always + hiện tại tiếp diễn diễn tả phàn nàn: are always losing.",
      whyWrong: {
        a: "do always lose không phải cấu trúc phàn nàn chuẩn với always + V-ing.",
        c: "did/lose đưa câu về quá khứ.",
        d: "have/lost không khớp mẫu always + V-ing để phàn nàn.",
      },
    }),
    mcq({
      id: "pc-12",
      difficulty: "hard",
      stem: "Be careful. The water ___ .",
      choices: {
        a: "boils",
        b: "is boiling",
        c: "boil",
        d: "boiled",
      },
      answer: "b",
      explanation: "Be careful và ngữ cảnh cảnh báo chỉ nước đang sôi lúc nói: is boiling.",
      whyWrong: {
        a: "boils hợp quy luật 'nước sôi ở 100 độ', không phải cảnh báo lúc này.",
        c: "boil thiếu be và chưa chia.",
        d: "boiled là quá khứ.",
      },
    }),
  ],
};
