import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const presentPerfect: TopicSeed = {
  id: "topic-present-perfect",
  slug: "present-perfect",
  name: "Present Perfect",
  gradeFrom: 8,
  gradeTo: 12,
  summary: "Việc nối với hiện tại, kinh nghiệm, hoặc kết quả còn thấy bây giờ.",
  purpose: "Nói một việc xảy ra trước lúc nói nhưng vẫn liên quan tới hiện tại.",
  usage: [
    "Kinh nghiệm: việc đã từng làm trong đời.",
    "Kết quả tới hiện tại: việc vừa xảy ra và còn thấy kết quả.",
    "Khoảng chưa kết thúc: today, this morning nếu buổi sáng chưa qua.",
  ].join("\n"),
  structure: [
    "Khẳng định: have / has + quá khứ phân từ (V3).",
    "Phủ định: thêm not.",
    "Câu hỏi: đảo have / has lên trước chủ ngữ.",
  ].join("\n"),
  affirmativePattern: "Chủ ngữ + have/has + V3.",
  negativePattern: "Chủ ngữ + have/has not + V3.",
  questionPattern: "Have/Has + chủ ngữ + V3?",
  signalWords: ["just", "already", "yet", "ever", "never", "since", "for", "so far"],
  examples: [
    { sentence: "I have seen this film twice.", note: "Kinh nghiệm, không nói lúc nào." },
    { sentence: "She has lived here since 2019.", note: "since kèm mốc bắt đầu, việc còn tiếp diễn." },
    { sentence: "They haven't finished yet.", note: "yet thường đứng ở câu phủ định hoặc câu hỏi." },
  ],
  commonMistakes: [
    { wrong: "I have see this film.", right: "I have seen this film.", why: "have đi với phân từ seen, không phải nguyên mẫu." },
    { wrong: "She has lived here for 2019.", right: "She has lived here since 2019.", why: "for cộng khoảng thời gian, since cộng mốc bắt đầu." },
    { wrong: "Did you ever been to Hoi An?", right: "Have you ever been to Hoi An?", why: "ever với kinh nghiệm dùng have, been là phân từ của be." },
  ],
  comparisons: [
    { with: "Past simple", note: "Hiện tại hoàn thành không gắn với một thời điểm đã khép như yesterday. Quá khứ đơn thì có." },
  ],
  prerequisiteSlugs: ["past-simple"],
  questions: [
    mcq({
      id: "pp-1",
      difficulty: "easy",
      stem: "I have ___ this film twice.",
      choices: { a: "see", b: "saw", c: "seen", d: "seeing" },
      answer: "c",
      explanation: "have đi với quá khứ phân từ. see có phân từ là seen.",
      whyWrong: {
        a: "see là nguyên mẫu.",
        b: "saw là quá khứ đơn, không đứng sau have.",
        d: "seeing là dạng -ing.",
      },
    }),
    mcq({
      id: "pp-2",
      difficulty: "easy",
      stem: "She has lived in this building ___ 2019.",
      choices: { a: "for", b: "since", c: "ago", d: "during" },
      answer: "b",
      explanation: "2019 là mốc bắt đầu, nên dùng since.",
      whyWrong: {
        a: "for cần một khoảng thời gian, ví dụ for six years.",
        c: "ago đứng sau khoảng thời gian và thường đi với quá khứ đơn.",
        d: "during không thay since trong cấu trúc này.",
      },
    }),
    mcq({
      id: "pp-3",
      difficulty: "medium",
      stem: "They ___ finished the group project yet.",
      choices: { a: "have", b: "haven't", c: "didn't", d: "don't" },
      answer: "b",
      explanation: "yet trong câu chưa hoàn thành dùng haven't finished.",
      whyWrong: {
        a: "have finished yet không phải câu phủ định. yet ở đây báo việc chưa xong.",
        c: "didn't finished không đúng dạng, và didn't không đi với yet theo kiểu này.",
        d: "don't không tạo thì hiện tại hoàn thành.",
      },
    }),
    mcq({
      id: "pp-4",
      difficulty: "medium",
      stem: "___ you ever been to Hoi An?",
      choices: { a: "Did", b: "Have", c: "Do", d: "Are" },
      answer: "b",
      explanation: "ever và been hỏi kinh nghiệm: Have you ever been.",
      whyWrong: {
        a: "Did you ever been sai vì sau did không dùng been.",
        c: "Do không đi với been.",
        d: "Are you ever been không phải câu hỏi kinh nghiệm.",
      },
    }),
    mcq({
      id: "pp-5",
      difficulty: "hard",
      stem: "I have known Linh ___ five years.",
      choices: { a: "since", b: "for", c: "ago", d: "from" },
      answer: "b",
      explanation: "five years là khoảng thời gian, dùng for.",
      whyWrong: {
        a: "since cần mốc, ví dụ since 2021.",
        c: "ago không đứng trong have known theo cách này.",
        d: "from không thay for trước một khoảng năm.",
      },
    }),
    mcq({
      id: "pp-6",
      difficulty: "hard",
      stem: "We ___ three lab reports this morning, and it is still morning.",
      choices: { a: "wrote", b: "have written", c: "write", d: "were writing" },
      answer: "b",
      explanation: "Buổi sáng chưa kết thúc, nên việc viết báo cáo nối tới hiện tại: have written.",
      whyWrong: {
        a: "wrote hợp hơn khi buổi sáng đã qua hẳn.",
        c: "write là thói quen, không phải số báo cáo đã viết.",
        d: "were writing nói hành động đang diễn ra trong quá khứ, không đếm kết quả.",
      },
    }),
    mcq({
      id: "pp-7",
      difficulty: "easy",
      stem: "Lan has ___ finished the online quiz.",
      choices: { a: "just", b: "yesterday", c: "ago", d: "last night" },
      answer: "a",
      explanation: "just đứng giữa has và phân từ khi việc vừa xong.",
      whyWrong: {
        b: "yesterday không đứng giữa has và finished; nó kéo câu về quá khứ đơn.",
        c: "ago cần khoảng thời gian phía trước và thường đi với quá khứ đơn.",
        d: "last night là mốc đã khép, không đặt giữa has và finished.",
      },
    }),
    mcq({
      id: "pp-8",
      difficulty: "easy",
      stem: "They have already ___ the class email.",
      choices: { a: "send", b: "sent", c: "sending", d: "sends" },
      answer: "b",
      explanation: "have already đi với quá khứ phân từ: sent.",
      whyWrong: {
        a: "send là nguyên mẫu, không đứng sau have.",
        c: "sending là dạng -ing.",
        d: "sends là hiện tại đơn ngôi thứ ba.",
      },
    }),
    mcq({
      id: "pp-9",
      difficulty: "medium",
      stem: "My brother ___ never ridden a motorbike.",
      choices: { a: "have", b: "has", c: "did", d: "is" },
      answer: "b",
      explanation: "brother số ít đi với has trong hiện tại hoàn thành: has never ridden.",
      whyWrong: {
        a: "have không đi với chủ ngữ số ít my brother.",
        c: "did không tạo cấu trúc never ridden.",
        d: "is không đứng trước never ridden.",
      },
    }),
    mcq({
      id: "pp-10",
      difficulty: "medium",
      stem: "___ she finished her homework yet?",
      choices: { a: "Does", b: "Did", c: "Has", d: "Is" },
      answer: "c",
      explanation: "yet trong câu hỏi hoàn thành dùng Has + chủ ngữ + phân từ.",
      whyWrong: {
        a: "Does không đi với finished ở dạng phân từ.",
        b: "Did she finished sai dạng, và yet kiểu này thuộc hiện tại hoàn thành.",
        d: "Is she finished yet hỏi trạng thái khác, không khớp mẫu has + V3.",
      },
    }),
    mcq({
      id: "pp-11",
      difficulty: "hard",
      stem: "Nam is not here. He has ___ to the library.",
      choices: { a: "been", b: "gone", c: "went", d: "go" },
      answer: "b",
      explanation: "gone nghĩa đã đi và vẫn chưa về, khớp với Nam is not here.",
      whyWrong: {
        a: "been nghĩa đã đến rồi quay về; lúc đó thường vẫn có mặt ở đây.",
        c: "went là quá khứ đơn, không đứng sau has.",
        d: "go là nguyên mẫu, không đứng sau has.",
      },
    }),
    mcq({
      id: "pp-12",
      difficulty: "hard",
      stem: "So far this year, our class ___ five charity events.",
      choices: { a: "organized", b: "has organized", c: "organizes", d: "was organizing" },
      answer: "b",
      explanation: "so far this year là khoảng thời gian chưa kết thúc, dùng has organized.",
      whyWrong: {
        a: "organized hợp hơn khi năm đã khép hoặc có mốc quá khứ cụ thể.",
        c: "organizes nói thói quen, không đếm kết quả tới nay.",
        d: "was organizing nói việc đang diễn ra trong quá khứ, không đếm tổng số.",
      },
    }),
  ],
};
