import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const quantifiers: TopicSeed = {
  id: "topic-quantifiers",
  slug: "quantifiers",
  name: "Quantifiers",
  gradeFrom: 7,
  gradeTo: 12,
  summary: "Lượng từ some, any, much, many, a lot of để nói số lượng không chính xác.",
  purpose: "Chỉ có bao nhiêu người, vật hoặc mức độ mà không cần số đếm cụ thể.",
  usage: [
    "some: thường ở câu khẳng định.",
    "any: ở câu phủ định và câu hỏi.",
    "many: với danh từ đếm được số nhiều.",
    "much: với danh từ không đếm được.",
    "a lot of: dùng được cho cả hai, nhất là câu khẳng định.",
  ].join("\n"),
  structure: [
    "Đếm được số nhiều: some / any / many + danh từ.",
    "Không đếm được: some / any / much + danh từ.",
    "a lot of / lots of: đi với cả danh từ đếm được số nhiều và không đếm được.",
  ].join("\n"),
  affirmativePattern: "There is/are + some / a lot of + danh từ.",
  negativePattern: "There isn't/aren't + any / much / many + danh từ.",
  questionPattern: "Is/Are there + any / much / many + danh từ?",
  signalWords: ["some", "any", "much", "many", "a lot of", "lots of"],
  examples: [
    {
      sentence: "I bought some apples at the market.",
      note: "some + apples trong câu khẳng định.",
    },
    {
      sentence: "There isn't much time left before the bell.",
      note: "time không đếm được → much trong câu phủ định.",
    },
    {
      sentence: "Do you have any questions about Unit 3?",
      note: "any thường đứng trong câu hỏi.",
    },
  ],
  commonMistakes: [
    {
      wrong: "I don't have some money.",
      right: "I don't have any money.",
      why: "Câu phủ định dùng any, không dùng some trong trường hợp này.",
    },
    {
      wrong: "How much books did you borrow?",
      right: "How many books did you borrow?",
      why: "books đếm được số nhiều → many.",
    },
    {
      wrong: "There are much students in the hall.",
      right: "There are many students in the hall.",
      why: "students đếm được → many hoặc a lot of, không dùng much.",
    },
  ],
  comparisons: [
    {
      with: "Much vs many vs a lot of",
      note: "much đi với không đếm được, many với đếm được số nhiều. a lot of thay cả hai, thường tự nhiên hơn trong câu khẳng định.",
    },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "quant-1",
      difficulty: "easy",
      stem: "I need ___ sugar for this cake.",
      choices: { a: "many", b: "some", c: "a", d: "few" },
      answer: "b",
      explanation: "sugar không đếm được trong câu khẳng định → some.",
      whyWrong: {
        a: "many chỉ đi với danh từ đếm được số nhiều.",
        c: "a sugar sai vì sugar không đếm từng đơn vị kiểu này.",
        d: "few đi với danh từ đếm được số nhiều, không với sugar.",
      },
    }),
    mcq({
      id: "quant-2",
      difficulty: "easy",
      stem: "Are there ___ chairs in that classroom?",
      choices: { a: "some", b: "any", c: "much", d: "a little" },
      answer: "b",
      explanation: "Câu hỏi yes/no thường dùng any với danh từ đếm được.",
      whyWrong: {
        a: "some ít gặp hơn trong câu hỏi yes/no kiểu này; any là lựa chọn chuẩn.",
        c: "much không đi với chairs.",
        d: "a little đi với không đếm được.",
      },
    }),
    mcq({
      id: "quant-3",
      difficulty: "easy",
      stem: "There aren't ___ eggs left in the fridge.",
      choices: { a: "some", b: "any", c: "much", d: "a lot" },
      answer: "b",
      explanation: "Câu phủ định dùng any.",
      whyWrong: {
        a: "some không dùng trong phủ định kiểu này.",
        c: "much không đi với eggs.",
        d: "a lot thiếu of và cũng không phải dạng phủ định chuẩn thay any.",
      },
    }),
    mcq({
      id: "quant-4",
      difficulty: "easy",
      stem: "How ___ students joined the club this semester?",
      choices: { a: "much", b: "many", c: "any", d: "little" },
      answer: "b",
      explanation: "students đếm được → How many.",
      whyWrong: {
        a: "How much dùng cho không đếm được.",
        c: "How any không phải cấu trúc hỏi số lượng.",
        d: "How little hỏi mức độ nhỏ của không đếm được, không khớp students.",
      },
    }),
    mcq({
      id: "quant-5",
      difficulty: "medium",
      stem: "There is ___ traffic on this road in rush hour.",
      choices: { a: "many", b: "a few", c: "a lot of", d: "several" },
      answer: "c",
      explanation: "traffic không đếm được → a lot of traffic.",
      whyWrong: {
        a: "many không đi với traffic.",
        b: "a few đi với đếm được số nhiều.",
        d: "several đi với đếm được số nhiều.",
      },
    }),
    mcq({
      id: "quant-6",
      difficulty: "medium",
      stem: "We don't have ___ time, so please hurry.",
      choices: { a: "many", b: "much", c: "a few", d: "several" },
      answer: "b",
      explanation: "time không đếm được trong câu phủ định → much.",
      whyWrong: {
        a: "many không đi với time.",
        c: "a few không đi với time và cũng mang nghĩa khẳng định số ít.",
        d: "several không đi với time.",
      },
    }),
    mcq({
      id: "quant-7",
      difficulty: "medium",
      stem: "She made ___ friends during the summer camp.",
      choices: { a: "much", b: "little", c: "a lot of", d: "any" },
      answer: "c",
      explanation: "friends đếm được số nhiều trong câu khẳng định → a lot of.",
      whyWrong: {
        a: "much không đi với friends.",
        b: "little đi với không đếm được.",
        d: "any thường ở phủ định hoặc nghi vấn, không phải khẳng định này.",
      },
    }),
    mcq({
      id: "quant-8",
      difficulty: "medium",
      stem: "Is there ___ milk in the bottle?",
      choices: { a: "many", b: "a few", c: "any", d: "several" },
      answer: "c",
      explanation: "Câu hỏi với danh từ không đếm được dùng any.",
      whyWrong: {
        a: "many không đi với milk.",
        b: "a few không đi với milk.",
        d: "several không đi với milk.",
      },
    }),
    mcq({
      id: "quant-9",
      difficulty: "hard",
      stem: "There is too ___ noise in this cafe for me to focus.",
      choices: { a: "many", b: "much", c: "few", d: "a few" },
      answer: "b",
      explanation: "noise không đếm được → too much noise.",
      whyWrong: {
        a: "too many đi với đếm được số nhiều.",
        c: "few đi với đếm được và mang nghĩa ít.",
        d: "a few cũng chỉ dùng với đếm được số nhiều.",
      },
    }),
    mcq({
      id: "quant-10",
      difficulty: "hard",
      stem: "Only ___ of the answers were correct, so he got a low mark.",
      choices: { a: "much", b: "little", c: "a little", d: "a few" },
      answer: "d",
      explanation: "answers đếm được → a few; only a few khớp ý chỉ đúng ít câu.",
      whyWrong: {
        a: "much không đi với answers.",
        b: "little đi với không đếm được.",
        c: "a little đi với không đếm được, không với answers.",
      },
    }),
    mcq({
      id: "quant-11",
      difficulty: "hard",
      stem: "Would you like ___ tea, or do you prefer water?",
      choices: { a: "any", b: "some", c: "many", d: "few" },
      answer: "b",
      explanation: "Lời mời/đề nghị lịch sự dùng some dù là câu hỏi.",
      whyWrong: {
        a: "any cũng gặp trong câu hỏi, nhưng lời mời lịch sự ưu tiên some.",
        c: "many không đi với tea theo cách này.",
        d: "few không đi với tea.",
      },
    }),
    mcq({
      id: "quant-12",
      difficulty: "hard",
      stem: "There were ___ people at the talk that some had to stand.",
      choices: {
        a: "so much",
        b: "too little",
        c: "so many",
        d: "not much",
      },
      answer: "c",
      explanation: "people đếm được và số đông đến mức phải đứng → so many people.",
      whyWrong: {
        a: "so much không đi với people.",
        b: "too little people sai hoàn toàn về lượng từ và nghĩa.",
        d: "not much không đi với people và trái với ý đông đến mức phải đứng.",
      },
    }),
  ],
};
