import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const relativeClauses: TopicSeed = {
  id: "topic-relative",
  slug: "relative-clauses",
  name: "Relative Clauses",
  gradeFrom: 10,
  gradeTo: 12,
  summary: "Mệnh đề quan hệ xác định người, vật, nơi chốn hoặc thời điểm.",
  purpose: "Thêm thông tin về một danh từ mà không viết thành câu thứ hai.",
  usage: [
    "who: chỉ người, làm chủ ngữ.",
    "whom: chỉ người, làm tân ngữ.",
    "whose: chỉ sở hữu.",
    "which: chỉ vật.",
    "when: chỉ thời điểm.",
  ].join("\n"),
  structure: [
    "Mẫu: danh từ + who / whom / whose / which / when + mệnh đề.",
    "Vị trí: đại từ quan hệ đứng sát danh từ nó thay thế.",
  ].join("\n"),
  affirmativePattern: "Danh từ + who/which + động từ.",
  negativePattern: "Danh từ + who/which + do/does/did not + V.",
  questionPattern: "Mệnh đề quan hệ nằm trong câu hỏi lớn, không tự đảo who lên đầu nếu who không phải từ hỏi.",
  signalWords: ["who", "whom", "whose", "which", "when"],
  examples: [
    { sentence: "The student who won the contest is in class 12A.", note: "who thay học sinh, làm chủ ngữ của won." },
    { sentence: "The woman whose son studies medicine lives next door.", note: "whose chỉ sở hữu." },
    { sentence: "I remember the day when we started grade 10.", note: "when thay cho thời điểm." },
  ],
  commonMistakes: [
    { wrong: "The student which won the prize.", right: "The student who won the prize.", why: "Người dùng who, which dùng cho vật." },
    { wrong: "The woman who son is a doctor.", right: "The woman whose son is a doctor.", why: "Sở hữu dùng whose, không dùng who." },
    { wrong: "The man which we met is a coach.", right: "The man whom we met is a coach.", why: "Người làm tân ngữ dùng whom trong bài tập dạng này." },
  ],
  comparisons: [
    { with: "Hai câu tách rời", note: "The student won the prize. She is in class 12A. Ghép lại: The student who won the prize is in class 12A." },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "rc-1",
      difficulty: "easy",
      stem: "The student ___ won the speech contest is in class 12A.",
      choices: { a: "which", b: "who", c: "whose", d: "where" },
      answer: "b",
      explanation: "student là người và làm chủ ngữ của won, dùng who.",
      whyWrong: {
        a: "which dành cho vật.",
        c: "whose cần một danh từ sở hữu ngay sau, ví dụ whose essay.",
        d: "where dành cho nơi chốn.",
      },
    }),
    mcq({
      id: "rc-2",
      difficulty: "easy",
      stem: "This is the novel ___ I told you about.",
      choices: { a: "who", b: "which", c: "whose", d: "where" },
      answer: "b",
      explanation: "novel là vật, dùng which.",
      whyWrong: {
        a: "who dành cho người.",
        c: "whose chỉ sở hữu, câu này không có danh từ bị sở hữu.",
        d: "where không thay một cuốn sách trong cấu trúc told you about.",
      },
    }),
    mcq({
      id: "rc-3",
      difficulty: "medium",
      stem: "The woman ___ son studies medicine lives next door.",
      choices: { a: "who", b: "which", c: "whose", d: "where" },
      answer: "c",
      explanation: "son thuộc về người phụ nữ, nên whose.",
      whyWrong: {
        a: "who son không chỉ được quan hệ sở hữu.",
        b: "which không dùng cho người và cũng không chỉ sở hữu.",
        d: "where chỉ nơi chốn.",
      },
    }),
    mcq({
      id: "rc-4",
      difficulty: "medium",
      stem: "Ha Long Bay is a place ___ many tourists visit in summer.",
      choices: { a: "who", b: "whose", c: "which", d: "when" },
      answer: "c",
      explanation: "visit cần tân ngữ, place đóng vai tân ngữ đó nên dùng which.",
      whyWrong: {
        a: "who không thay một địa danh.",
        b: "whose cần danh từ sở hữu phía sau.",
        d: "when thay thời gian, không thay nơi là tân ngữ của visit.",
      },
    }),
    mcq({
      id: "rc-5",
      difficulty: "hard",
      stem: "The man ___ we met at the gate is our new coach.",
      choices: { a: "which", b: "whom", c: "whose", d: "when" },
      answer: "b",
      explanation: "man là người và là tân ngữ của met, dùng whom.",
      whyWrong: {
        a: "which không thay người.",
        c: "whose cần một danh từ ngay sau để chỉ cái được sở hữu.",
        d: "when thay thời điểm, không thay người.",
      },
    }),
    mcq({
      id: "rc-6",
      difficulty: "hard",
      stem: "I still remember the day ___ we started grade 10.",
      choices: { a: "which", b: "who", c: "when", d: "whose" },
      answer: "c",
      explanation: "the day là thời điểm, mệnh đề sau đủ chủ ngữ và động từ, dùng when.",
      whyWrong: {
        a: "which sẽ cần giới từ, ví dụ on which. Câu này dùng when cho thời điểm.",
        b: "who thay người.",
        d: "whose chỉ sở hữu.",
      },
    }),
    mcq({
      id: "rc-7",
      difficulty: "easy",
      stem: "I bought a phone ___ has a good camera.",
      choices: { a: "who", b: "which", c: "whose", d: "when" },
      answer: "b",
      explanation: "phone là vật và làm chủ ngữ của has, dùng which.",
      whyWrong: {
        a: "who dành cho người.",
        c: "whose cần danh từ sở hữu ngay sau, ví dụ whose camera.",
        d: "when dành cho thời điểm.",
      },
    }),
    mcq({
      id: "rc-8",
      difficulty: "easy",
      stem: "This is the café ___ we usually meet after school.",
      choices: { a: "who", b: "whose", c: "where", d: "whom" },
      answer: "c",
      explanation: "café là nơi chốn, mệnh đề sau đã có chủ ngữ we, dùng where.",
      whyWrong: {
        a: "who thay người, không thay quán cà phê.",
        b: "whose chỉ sở hữu và cần danh từ ngay sau.",
        d: "whom thay người làm tân ngữ, không thay nơi chốn.",
      },
    }),
    mcq({
      id: "rc-9",
      difficulty: "medium",
      stem: "The boy ___ bicycle was stolen reported it to the police.",
      choices: { a: "who", b: "which", c: "whose", d: "when" },
      answer: "c",
      explanation: "bicycle thuộc về the boy, nên whose.",
      whyWrong: {
        a: "who bicycle không diễn đạt quan hệ sở hữu.",
        b: "which không dùng cho người và cũng không chỉ sở hữu ở đây.",
        d: "when thay thời điểm.",
      },
    }),
    mcq({
      id: "rc-10",
      difficulty: "medium",
      stem: "August is the month ___ we often have heavy rain.",
      choices: { a: "who", b: "which", c: "when", d: "whose" },
      answer: "c",
      explanation: "the month là thời điểm, mệnh đề sau đủ chủ ngữ và động từ, dùng when.",
      whyWrong: {
        a: "who thay người.",
        b: "which cần giới từ, ví dụ in which; câu này chọn when.",
        d: "whose chỉ sở hữu.",
      },
    }),
    mcq({
      id: "rc-11",
      difficulty: "hard",
      stem: "The doctor ___ they called last night is my uncle.",
      choices: { a: "which", b: "whom", c: "whose", d: "when" },
      answer: "b",
      explanation: "doctor là người và là tân ngữ của called, dùng whom.",
      whyWrong: {
        a: "which không thay người.",
        c: "whose cần danh từ sở hữu ngay sau.",
        d: "when thay thời điểm, không thay người.",
      },
    }),
    mcq({
      id: "rc-12",
      difficulty: "hard",
      stem: "The laptop ___ she uses for design is quite new.",
      choices: { a: "who", b: "whom", c: "which", d: "when" },
      answer: "c",
      explanation: "laptop là vật và là tân ngữ của uses, dùng which.",
      whyWrong: {
        a: "who dành cho người.",
        b: "whom dành cho người làm tân ngữ, không thay vật.",
        d: "when dành cho thời điểm.",
      },
    }),
  ],
};
