import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const reportedSpeech: TopicSeed = {
  id: "topic-reported-speech",
  slug: "reported-speech",
  name: "Reported Speech",
  gradeFrom: 10,
  gradeTo: 12,
  summary: "Tường thuật lời nói của người khác, thường lùi thì và đổi đại từ, trạng từ thời gian.",
  purpose: "Kể lại lời nói, câu hỏi hoặc lời yêu cầu mà không trích nguyên văn trong ngoặc kép.",
  usage: [
    "Lùi thì: khi động từ tường thuật ở quá khứ (said, told, asked), thì trong lời nói thường lùi một bậc.",
    "Đại từ và từ chỉ thời gian: đổi cho khớp người nói mới.",
    "told: phải có tân ngữ người.",
    "said: thường không có tân ngữ người.",
  ].join("\n"),
  structure: [
    "Câu kể: chủ ngữ + said / told + (that) + mệnh đề đã lùi thì.",
    "Câu hỏi: asked + if / whether hoặc từ hỏi + chủ ngữ + động từ, không đảo.",
  ].join("\n"),
  affirmativePattern: "S + said (that) + S + V (đã lùi thì).",
  negativePattern: "S + said (that) + S + did not / was not / would not + ...",
  questionPattern: "S + asked + if/whether / wh- + S + V (trật tự khẳng định).",
  signalWords: ["said", "told", "asked", "that", "the day before", "the following day"],
  examples: [
    {
      sentence: 'She said, "I am tired." → She said (that) she was tired.',
      note: "am lùi thành was; I đổi thành she.",
    },
    {
      sentence: 'He told me, "I finished the test." → He told me (that) he had finished the test.',
      note: "Past simple lùi thành past perfect; told cần tân ngữ me.",
    },
    {
      sentence: 'They asked, "Where do you live?" → They asked where I lived.',
      note: "Bỏ đảo ngữ do/you; where + chủ ngữ + động từ đã lùi.",
    },
  ],
  commonMistakes: [
    {
      wrong: "He said me that he was busy.",
      right: "He told me that he was busy. / He said that he was busy.",
      why: "said không đi với tân ngữ người trực tiếp như said me; dùng told me hoặc bỏ me.",
    },
    {
      wrong: 'She said she is tired. (khi lời gốc ở quá khứ tường thuật)',
      right: "She said she was tired.",
      why: "Động từ tường thuật quá khứ thường kéo theo lùi thì: am/is → was.",
    },
    {
      wrong: "He asked where did I live.",
      right: "He asked where I lived.",
      why: "Câu hỏi tường thuật không đảo did + chủ ngữ; dùng trật tự khẳng định.",
    },
  ],
  comparisons: [
    {
      with: "Direct speech",
      note: 'Direct giữ nguyên lời và dấu ngoặc: "I will call you tomorrow." Reported đổi thì và thời gian: She said she would call me the following day.',
    },
  ],
  prerequisiteSlugs: ["past-simple", "past-perfect"],
  questions: [
    mcq({
      id: "rs-1",
      difficulty: "easy",
      stem: 'Lan said, "I am hungry." → Lan said that she ___ hungry.',
      choices: { a: "is", b: "was", c: "has been", d: "will be" },
      answer: "b",
      explanation: "am ở lời trực tiếp lùi thành was khi said ở quá khứ.",
      whyWrong: {
        a: "is giữ thì hiện tại, không lùi theo quy tắc tường thuật với said.",
        c: "has been là hiện tại hoàn thành, không phải dạng lùi của am.",
        d: "will be là tương lai, không khớp lời gốc am.",
      },
    }),
    mcq({
      id: "rs-2",
      difficulty: "easy",
      stem: 'Tom said, "I like football." → Tom said that he ___ football.',
      choices: { a: "likes", b: "liked", c: "has liked", d: "will like" },
      answer: "b",
      explanation: "Present simple like lùi thành past simple liked.",
      whyWrong: {
        a: "likes vẫn là hiện tại, chưa lùi thì.",
        c: "has liked không phải bước lùi chuẩn của like trong mẫu này.",
        d: "will like đổi nghĩa sang tương lai.",
      },
    }),
    mcq({
      id: "rs-3",
      difficulty: "easy",
      stem: "He ___ me that the meeting started at eight.",
      choices: { a: "said", b: "told", c: "asked", d: "spoke" },
      answer: "b",
      explanation: "Có tân ngữ người me nên dùng told me that...",
      whyWrong: {
        a: "said me that là sai; said không nhận tân ngữ người như vậy.",
        c: "asked dùng cho câu hỏi, không khớp mệnh đề that thông tin.",
        d: "spoke me that không phải cấu trúc tường thuật chuẩn.",
      },
    }),
    mcq({
      id: "rs-4",
      difficulty: "easy",
      stem: 'She said, "I can swim." → She said that she ___ swim.',
      choices: { a: "can", b: "could", c: "will", d: "may" },
      answer: "b",
      explanation: "can thường lùi thành could trong lời tường thuật quá khứ.",
      whyWrong: {
        a: "can giữ nguyên khi không lùi; với said quá khứ bài thi thường đòi could.",
        c: "will không thay cho can.",
        d: "may mang nghĩa khác, không phải lùi của can.",
      },
    }),
    mcq({
      id: "rs-5",
      difficulty: "medium",
      stem: 'He said, "I will call you tomorrow." → He said that he would call me ___.',
      choices: {
        a: "tomorrow",
        b: "the following day",
        c: "yesterday",
        d: "the day before",
      },
      answer: "b",
      explanation: "tomorrow đổi thành the following day / the next day khi tường thuật.",
      whyWrong: {
        a: "tomorrow gắn với thời điểm nói gốc, thường phải đổi trong reported speech.",
        c: "yesterday là quá khứ so với hôm nay, không thay tomorrow.",
        d: "the day before thay cho yesterday, không phải tomorrow.",
      },
    }),
    mcq({
      id: "rs-6",
      difficulty: "medium",
      stem: 'Mai said, "I bought this book yesterday." → Mai said that she ___ that book the day before.',
      choices: { a: "bought", b: "has bought", c: "had bought", d: "was buying" },
      answer: "c",
      explanation: "Past simple bought lùi thành past perfect had bought.",
      whyWrong: {
        a: "bought chưa lùi thêm một bậc so với lời gốc quá khứ.",
        b: "has bought là hiện tại hoàn thành, không phải dạng lùi chuẩn.",
        d: "was buying là quá khứ tiếp diễn, đổi nghĩa hành động.",
      },
    }),
    mcq({
      id: "rs-7",
      difficulty: "medium",
      stem: '"Where do you live?" she asked me. → She asked me where ___.',
      choices: {
        a: "did I live",
        b: "I lived",
        c: "do I live",
        d: "I live",
      },
      answer: "b",
      explanation: "Câu hỏi tường thuật: từ hỏi + chủ ngữ + động từ đã lùi, không đảo.",
      whyWrong: {
        a: "did I live vẫn đảo như câu hỏi trực tiếp.",
        c: "do I live vừa đảo vừa chưa lùi thì.",
        d: "I live đúng trật tự nhưng chưa lùi present → past.",
      },
    }),
    mcq({
      id: "rs-8",
      difficulty: "medium",
      stem: '"Did you finish the homework?" the teacher asked. → The teacher asked if I ___ the homework.',
      choices: {
        a: "am finishing",
        b: "had finished",
        c: "have finished",
        d: "finish",
      },
      answer: "b",
      explanation: "Câu hỏi Yes/No dùng if; past simple trong lời gốc lùi thành past perfect had finished.",
      whyWrong: {
        a: "am finishing là hiện tại tiếp diễn, không phải dạng lùi của Did you finish.",
        c: "have finished là hiện tại hoàn thành, chưa lùi theo asked ở quá khứ.",
        d: "finish là hiện tại đơn, sai thì sau động từ tường thuật quá khứ.",
      },
    }),
    mcq({
      id: "rs-9",
      difficulty: "hard",
      stem: '"Don\'t touch the wire," the worker said to us. → The worker told us ___ the wire.',
      choices: {
        a: "to not touch",
        b: "not to touch",
        c: "do not touch",
        d: "not touching",
      },
      answer: "b",
      explanation: "Mệnh lệnh phủ định tường thuật: told + O + not to + V.",
      whyWrong: {
        a: "to not touch đảo vị trí not; mẫu chuẩn là not to touch.",
        c: "do not touch còn là lời trực tiếp, không phải dạng told us...",
        d: "not touching dùng danh động từ, không phải mẫu mệnh lệnh tường thuật.",
      },
    }),
    mcq({
      id: "rs-10",
      difficulty: "hard",
      stem: '"I have already sent the email," she said. → She said that she ___ the email.',
      choices: {
        a: "already sent",
        b: "has already sent",
        c: "had already sent",
        d: "was already sending",
      },
      answer: "c",
      explanation: "Present perfect have sent lùi thành past perfect had sent.",
      whyWrong: {
        a: "already sent thiếu trợ động từ hoàn thành had.",
        b: "has already sent giữ hiện tại hoàn thành, chưa lùi.",
        d: "was already sending đổi sang tiếp diễn, lệch nghĩa hoàn tất.",
      },
    }),
    mcq({
      id: "rs-11",
      difficulty: "hard",
      stem: '"Why are you crying?" he asked her. → He asked her why ___.',
      choices: {
        a: "was she crying",
        b: "she was crying",
        c: "is she crying",
        d: "she is crying",
      },
      answer: "b",
      explanation: "are crying lùi thành was crying; giữ trật tự chủ ngữ + động từ.",
      whyWrong: {
        a: "was she crying vẫn đảo như câu hỏi trực tiếp.",
        c: "is she crying vừa đảo vừa chưa lùi thì.",
        d: "she is crying đúng trật tự nhưng chưa lùi are → was.",
      },
    }),
    mcq({
      id: "rs-12",
      difficulty: "hard",
      stem: '"We must leave now," they said. → They said that they ___ leave then.',
      choices: { a: "must", b: "had to", c: "have to", d: "ought" },
      answer: "b",
      explanation: "must chỉ nghĩa bắt buộc hiện tại thường tường thuật thành had to; now → then.",
      whyWrong: {
        a: "must đôi khi giữ nguyên, nhưng với now→then bài tập lùi thì thường chọn had to.",
        c: "have to là hiện tại, chưa khớp tường thuật quá khứ.",
        d: "ought thiếu to và không phải dạng lùi chuẩn của must.",
      },
    }),
  ],
};
