import { mcq } from "../helpers";
import type { TopicSeed } from "../types";

export const wordFormation: TopicSeed = {
  id: "topic-word-formation",
  slug: "word-formation",
  name: "Word Formation",
  gradeFrom: 10,
  gradeTo: 12,
  summary: "Tạo danh từ, tính từ, trạng từ hoặc động từ từ một gốc từ cho khớp chức năng trong câu.",
  purpose: "Điền dạng từ đúng vào chỗ trống theo vị trí ngữ pháp và nghĩa câu.",
  usage: [
    "Sau mạo từ, tính từ sở hữu: thường cần danh từ.",
    "Trước danh từ, sau be: thường cần tính từ.",
    "Trước tính từ, động từ: thường cần trạng từ.",
    "Sau to, trợ động từ: cần động từ nguyên mẫu.",
    "un-, in-, im-, ir-, dis-: tiền tố thường tạo nghĩa phủ định.",
  ].join("\n"),
  structure: [
    "Hậu tố: gốc từ + -tion, -ment, -ness, -ful, -less, -ous, -ly, -ise/-ize, -en... để ra từ đúng loại.",
    "Tiền tố: un-, re-, pre-... + gốc từ để đổi nghĩa.",
  ].join("\n"),
  affirmativePattern: "Chọn N / Adj / Adv / V khớp vị trí: a ___ decision; She spoke ___; They ___ the plan.",
  negativePattern: "Dùng dạng phủ định đúng loại: unfair, impossible, carefully ≠ careless khi nghĩa khác.",
  questionPattern: "Trong câu có chỗ trống, hỏi dạng nào của (GỐC TỪ) là đúng.",
  signalWords: ["noun", "adjective", "adverb", "verb", "-tion", "-ly"],
  examples: [
    {
      sentence: "Her decision surprised everyone. (decide → decision)",
      note: "Sau tính từ sở hữu Her cần danh từ.",
    },
    {
      sentence: "He answered the question carefully. (care → carefully)",
      note: "Bổ nghĩa cho answered cần trạng từ.",
    },
    {
      sentence: "The news made us hopeful about the result. (hope → hopeful)",
      note: "Sau made us cần tính từ chỉ trạng thái.",
    },
  ],
  commonMistakes: [
    {
      wrong: "She spoke careful in the interview.",
      right: "She spoke carefully in the interview.",
      why: "Bổ nghĩa động từ spoke cần trạng từ carefully, không dùng tính từ careful.",
    },
    {
      wrong: "His choose was wise.",
      right: "His choice was wise.",
      why: "Sau His cần danh từ choice, không dùng động từ choose.",
    },
    {
      wrong: "They successed in the contest.",
      right: "They succeeded in the contest.",
      why: "Cần động từ succeeded; success là danh từ.",
    },
  ],
  comparisons: [
    {
      with: "Synonym choice",
      note: "Chọn từ đồng nghĩa hỏi nghĩa. Word formation giữ cùng họ từ nhưng đổi loại từ cho khớp vị trí trong câu.",
    },
  ],
  prerequisiteSlugs: ["present-simple"],
  questions: [
    mcq({
      id: "wf-1",
      difficulty: "easy",
      stem: "Her sudden ___ surprised the whole class. (DECIDE)",
      choices: { a: "decide", b: "decision", c: "decisive", d: "decisively" },
      answer: "b",
      explanation: "Sau tính từ sở hữu Her và trước động từ cần danh từ decision.",
      whyWrong: {
        a: "decide là động từ, không đứng sau Her như danh từ chủ ngữ.",
        c: "decisive là tính từ, cần danh từ phía sau hoặc đứng sau be.",
        d: "decisively là trạng từ, không làm chủ ngữ.",
      },
    }),
    mcq({
      id: "wf-2",
      difficulty: "easy",
      stem: "Please drive ___ near the school gate. (CARE)",
      choices: { a: "care", b: "careful", c: "carefully", d: "carelessness" },
      answer: "c",
      explanation: "Bổ nghĩa động từ drive cần trạng từ carefully.",
      whyWrong: {
        a: "care là danh từ/động từ, không bổ nghĩa drive đúng cách ở đây.",
        b: "careful là tính từ, thường đứng trước danh từ hoặc sau be.",
        d: "carelessness là danh từ, sai loại từ và sai nghĩa.",
      },
    }),
    mcq({
      id: "wf-3",
      difficulty: "easy",
      stem: "The new park is a ___ place for evening walks. (PEACE)",
      choices: { a: "peace", b: "peaceful", c: "peacefully", d: "peacemaker" },
      answer: "b",
      explanation: "Trước danh từ place cần tính từ peaceful.",
      whyWrong: {
        a: "peace là danh từ; a peace place không chuẩn.",
        c: "peacefully là trạng từ, không đứng giữa a và place.",
        d: "peacemaker là danh từ chỉ người, lệch nghĩa chỗ trống.",
      },
    }),
    mcq({
      id: "wf-4",
      difficulty: "easy",
      stem: "They hope to ___ the old building next year. (MODERN)",
      choices: { a: "modern", b: "modernity", c: "modernise", d: "modernly" },
      answer: "c",
      explanation: "Sau to cần động từ nguyên mẫu: modernise (hoặc modernize).",
      whyWrong: {
        a: "modern là tính từ, không đứng sau to như động từ.",
        b: "modernity là danh từ.",
        d: "modernly không phải dạng động từ chuẩn và ít dùng.",
      },
    }),
    mcq({
      id: "wf-5",
      difficulty: "medium",
      stem: "His ___ to help the victims was widely praised. (WILLING)",
      choices: {
        a: "willing",
        b: "willingly",
        c: "willingness",
        d: "unwilling",
      },
      answer: "c",
      explanation: "Sau His và trước to help cần danh từ willingness.",
      whyWrong: {
        a: "willing là tính từ.",
        b: "willingly là trạng từ.",
        d: "unwilling là tính từ phủ định, vừa sai loại vừa trái nghĩa câu khen.",
      },
    }),
    mcq({
      id: "wf-6",
      difficulty: "medium",
      stem: "The scientist explained the idea very ___. (CLEAR)",
      choices: { a: "clear", b: "clearly", c: "clarity", d: "clearness" },
      answer: "b",
      explanation: "very + trạng từ bổ nghĩa explained: clearly.",
      whyWrong: {
        a: "clear là tính từ; sau explained cần trạng từ.",
        c: "clarity là danh từ.",
        d: "clearness là danh từ, không bổ nghĩa động từ.",
      },
    }),
    mcq({
      id: "wf-7",
      difficulty: "medium",
      stem: "It is ___ to finish the report without more data. (POSSIBLE)",
      choices: {
        a: "possible",
        b: "possibly",
        c: "impossible",
        d: "possibility",
      },
      answer: "c",
      explanation: "without more data cho nghĩa phủ định → impossible sau is.",
      whyWrong: {
        a: "possible trái với ngữ cảnh thiếu dữ liệu.",
        b: "possibly là trạng từ, không đứng sau is như bổ ngữ tính từ.",
        d: "possibility là danh từ; cần It is a possibility... mới đúng.",
      },
    }),
    mcq({
      id: "wf-8",
      difficulty: "medium",
      stem: "Regular exercise can ___ your heart. (STRONG)",
      choices: { a: "strong", b: "strength", c: "strengthen", d: "strongly" },
      answer: "c",
      explanation: "Sau can cần động từ nguyên mẫu: strengthen.",
      whyWrong: {
        a: "strong là tính từ.",
        b: "strength là danh từ.",
        d: "strongly là trạng từ, không phải động từ sau can.",
      },
    }),
    mcq({
      id: "wf-9",
      difficulty: "hard",
      stem: "The manager spoke about the ___ of teamwork in the project. (IMPORTANT)",
      choices: {
        a: "important",
        b: "importantly",
        c: "importance",
        d: "unimportant",
      },
      answer: "c",
      explanation: "Sau the và trước of cần danh từ importance.",
      whyWrong: {
        a: "important là tính từ; the important of là sai.",
        b: "importantly là trạng từ.",
        d: "unimportant là tính từ phủ định, sai loại và lệch nghĩa câu.",
      },
    }),
    mcq({
      id: "wf-10",
      difficulty: "hard",
      stem: "She looked ___ when she heard she had won the prize. (HAPPY)",
      choices: { a: "happy", b: "happily", c: "happiness", d: "unhappy" },
      answer: "a",
      explanation: "looked là linking verb → cần tính từ happy chỉ vẻ/trạng thái.",
      whyWrong: {
        b: "happily là trạng từ; look happily ít dùng và không phải mẫu cảm xúc sau look.",
        c: "happiness là danh từ.",
        d: "unhappy trái nghĩa với thắng giải.",
      },
    }),
    mcq({
      id: "wf-11",
      difficulty: "hard",
      stem: "His explanation was so ___ that nobody asked further questions. (CONVINCE)",
      choices: {
        a: "convince",
        b: "conviction",
        c: "convincing",
        d: "convincingly",
      },
      answer: "c",
      explanation: "Sau was so cần tính từ: convincing.",
      whyWrong: {
        a: "convince là động từ.",
        b: "conviction là danh từ.",
        d: "convincingly là trạng từ; so convincingly cần động từ chủ động khác cấu trúc.",
      },
    }),
    mcq({
      id: "wf-12",
      difficulty: "hard",
      stem: "They argued ___, so the chair had to stop the meeting. (ANGRY)",
      choices: { a: "angry", b: "angrily", c: "anger", d: "angrier" },
      answer: "b",
      explanation: "Bổ nghĩa động từ argued cần trạng từ angrily.",
      whyWrong: {
        a: "angry là tính từ, không bổ nghĩa argued trực tiếp.",
        c: "anger là danh từ.",
        d: "angrier là so sánh hơn của tính từ, sai loại từ tại chỗ trống.",
      },
    }),
  ],
};
